milli/src/search/criteria/asc_desc.rs

Resolves https://github.com/meilisearch/milli/issues/49

feat(search, criteria): const candidates threshold

---

milli/src/criterion.rs

Resolves https://github.com/meilisearch/milli/issues/129

fix(criterion): compile asc/desc regex only once

---

milli/src/index.rs
milli/src/update/index_documents/mod.rs

First (and simple) implementation of fields distribution for https://github.com/meilisearch/milli/issues/113

feat(index): introduce fields_ids_distribution

---

milli/src/search/mod.rs
milli/src/search/query_tree.rs
milli/src/update/settings.rs

Stop words

---

milli/src/search/mod.rs
milli/src/search/query_tree.rs

Resolves https://github.com/meilisearch/milli/issues/147

Support query words limit

---

http-ui/src/main.rs
milli/src/search/criteria/proximity.rs

I'm going to do a lot of small PR file by file to avoid conflicts as much as possible, merge as soon as you can and I'll do another file 😉

Make clippy happy

---

milli/src/search/criteria/proximity.rs

Add a threshold on proximity when choosing between linear and set algorithm

Optimize proximity criterion

---

milli/src/index.rs
milli/src/update/index_documents/mod.rs
milli/src/update/settings.rs

Resolves https://github.com/meilisearch/milli/issues/171

Disable autogenerate_docids by default

---

.github/workflows/test.yml

remove testing on main since we now use bors for merging.

remove tests on main

---

milli/src/search/criteria/proximity.rs

Fix plain sweep algorithm after creating some tests on proximity.

Fix plane sweep algorithm

---

milli/src/search/matching_words.rs
milli/src/search/mod.rs
milli/src/search/query_tree.rs

Make the MatchingWords return the number of matching bytes using a custom Levenshtein algorithm.
Fix #138

Make the MatchingWords return the number of matching bytes

---

benchmarks/scripts/compare.sh
benchmarks/scripts/list.sh

... and provide a script to list all the available benchmarks

remove s3cmd dependency 

---

http-ui/src/main.rs

I just noticed that `http-ui` was not compiling on `main`.
I'm not sure this is the best fix, but it works 👀

Fix http-ui

---

.github/workflows/test.yml
benchmarks/benches/songs.rs
benchmarks/benches/utils.rs
benchmarks/benches/wiki.rs

Check the benchmarks in the CI

---

milli/src/update/delete_documents.rs

We were previously using the hardcoded "id" primary key when deleting documents.

Use the index primary key when deleting documents

---

milli/src/index.rs
milli/src/lib.rs
milli/src/update/clear_documents.rs
milli/src/update/delete_documents.rs
milli/src/update/index_documents/mod.rs
milli/src/update/index_documents/transform.rs

Field distribution

---

milli/src/update/index_documents/store.rs

Closes #191, and resolves #140.

Warn for when a key is too large for LMDB

---

Cargo.lock
benchmarks/Cargo.toml
helpers/Cargo.toml
http-ui/Cargo.toml
infos/Cargo.toml
milli/Cargo.toml
milli/src/update/index_documents/store.rs
search/Cargo.toml

We were indexing every searchable field as filterable, this was a mistake.

Fix unconditional facet indexing

---

Cargo.lock
benchmarks/Cargo.toml

Import exactly the same dependency as milli instead of a wildcard that can do anything

Fix the benchmarks dependencies

---

milli/src/search/matching_words.rs

related to https://github.com/meilisearch/MeiliSearch/issues/1441

Fix matching lenghth in matching_words

---

.github/workflows/benchmarks.yml
benchmarks/Cargo.toml
benchmarks/README.md
benchmarks/benches/indexing.rs
benchmarks/build.rs

closes #274 
I don't really know how much time this will take on our bench machine. I'm afraid the wiki dataset will take a really long time to bench (it takes 1h30 on my computer).
If you are ok with it, I would like to merge this first PR since it introduces a first set of benchmarks and see how much time it takes in reality on our setup.

Add benchmarks for indexing

---

milli/src/index.rs
milli/src/search/criteria/asc_desc.rs
milli/src/search/facet/facet_distribution.rs
milli/src/search/facet/filter_condition.rs
milli/src/search/mod.rs
milli/src/update/delete_documents.rs
milli/src/update/index_documents/mod.rs
milli/src/update/settings.rs

Fix https://github.com/meilisearch/meilisearch/issues/1505.
fix https://github.com/meilisearch/MeiliSearch/issues/1529

Make sure that the relevancy is not impacted by other settings

---

milli/src/index.rs

Fix a bug found by @irevoire when benchmarking the search.

Fix invalid faceted documents ids buffer size

---

.github/workflows/rust.yml

Resolves https://github.com/meilisearch/milli/issues/326

Remove `beta` compilation in CI

---

milli/src/update/index_documents/store.rs

Resolves https://github.com/meilisearch/milli/issues/263

Wrap long values into BStr for warn logs

---

helpers/Cargo.toml
http-ui/Cargo.toml
infos/Cargo.toml
milli/Cargo.toml
search/Cargo.toml

Breaking because of the new indexer that implies DB changes #308

Update version for the next release (v0.12.0)

---

milli/src/update/index_documents/extract/extract_docid_word_positions.rs
milli/src/update/index_documents/helpers/mod.rs

Related to [#1677](https://github.com/meilisearch/MeiliSearch/issues/1677)

Fix mdb val size error

---

benchmarks/README.md
benchmarks/scripts/compare.sh

This modification allow us to compare more than 2 benchmarks or to only print the results of one benchmark

Improve the benchmark comparison script

---

helpers/Cargo.toml
http-ui/Cargo.toml
infos/Cargo.toml
milli/Cargo.toml
search/Cargo.toml

Release containing the geosearch, cf #322

Update version for the next release (v0.14.0)

---

milli/src/asc_desc.rs
milli/src/criterion.rs
milli/src/error.rs
milli/src/lib.rs
milli/src/search/criteria/mod.rs
milli/src/search/mod.rs

Rewrite most of geosearch error handling and another batch of tests on the criterion parsing.

Geosearch error handling

---

milli/src/update/index_documents/mod.rs

The bug is not present in the newer milli version.
Related to [Meilisearch#1716](https://github.com/meilisearch/MeiliSearch/issues/1716)

Add test checking the bug reported in meilisearch issue 1716

---

milli/src/asc_desc.rs

@Kerollmops This should be the last PR for the geosearch and error handling, sorry for doing it in so many steps :grimacing:

Improve error message for bad sort syntax with geosearch

---

milli/src/error.rs

Fixes #365

---

milli/src/update/index_documents/mod.rs

Revert "Change chunk size to 4MiB to fit more the end user usage"

---

milli/src/asc_desc.rs
milli/src/search/facet/filter_condition.rs
milli/src/search/facet/grammar.pest

And I missed _another_ reserved keyword error message in the filter :(

Reserved keyword error message

---

milli/src/error.rs

Change forgotten error messages

Change last error messages

---

cli/Cargo.toml
helpers/Cargo.toml
http-ui/Cargo.toml
infos/Cargo.toml
milli/Cargo.toml
milli/src/criterion.rs
milli/src/error.rs

Fixes Meilisearch [PR comment](https://github.com/meilisearch/MeiliSearch/pull/1873#issuecomment-959786406)

Change Attribute and Ranking rules errors

---

milli/src/update/delete_documents.rs
milli/src/update/index_documents/mod.rs

Inprove the returned meta when performing document additions and deletions:
- On document addition return the number of indexed documents and the total number of documents in the index after the indexion
- On document deletion return the number of deleted documents, and the remaining number of documents in the index after the deletion is performed
I also fixed a potential bug when performing a document deletion and the primary key couldn't be found: before we assumed that the db was empty and returned that no documents were deleted, but since we checked before that the db wasn't empty, entering this branch is actually a bug, and now returns a 'MissingPrimaryKey' error.

improve update result types

---

cli/Cargo.toml
helpers/Cargo.toml
http-ui/Cargo.toml
infos/Cargo.toml
milli/Cargo.toml

Update milli 0.21.0

---

filter-parser/fuzz/.gitignore

Reintroduce the gitignore in the fuzz directory

Reintroduce the gitignore for the fuzzer

---

benchmarks/benches/indexing.rs
benchmarks/build.rs

Hey @irevoire, could you please add the new benchmarks into influx?

Benchmark multi batch indexing

---

milli/src/error.rs

I've created a test case to handle the new error formatting behavior, but I'm not sure if:
- this is the right place to add the test?
- this is the best way to test this behavior?
And I'm not sure also regarding the `match` implementation, is this something required? Or maybe just an `if` statement is ok as well?
I left the two messages literally without "reusing the prefix" in the implementation because I think this could help the "searchability" of the error in the future.
Fixes https://github.com/meilisearch/meilisearch/issues/2140

Add a new error message when the `valid_fields` is empty

---

milli/src/update/word_prefix_docids.rs
milli/src/update/word_prefix_pair_proximity_docids.rs
milli/src/update/words_prefix_position_docids.rs

This PR makes the prefix database updates to avoid iterating on big grenad files when it is unnecessary. We introduced this regression in #436 but it went unnoticed.
---
According to the following benchmark results, we take more time when we index documents in one run than before #436. It looks like it is probably due to the fact that, now, instead of computing the prefixes database by iterating on the LMDB we directly iterate on the grenad file. Those could be slower to iterate on and could be the slowdown cause.
I just pushed a commit that tests this branch with the new unreleased version of grenad where some work was done to speed up the iteration on grenad files. [The benchmarks for this last commit](https://github.com/meilisearch/milli/actions/runs/1927187408) are currently running. …

Avoid iterating on big databases when useless

---

milli/src/search/criteria/proximity.rs

Was passing by plane sweep algorithm to find some inspiration, and I discover that we have useless variables that were not detected because of the recursive function.

Remove useless variables in proximity

---

cli/Cargo.toml
helpers/Cargo.toml
http-ui/Cargo.toml
infos/Cargo.toml
milli/Cargo.toml

From v0.23.1 to v0.24.1 since we had an issue with the versionning for the previous release

Update version (v0.24.1)

---

cli/src/main.rs
infos/src/main.rs
milli/src/index.rs
milli/src/lib.rs
milli/src/search/criteria/mod.rs
milli/src/search/query_tree.rs
milli/src/update/clear_documents.rs
milli/src/update/delete_documents.rs
milli/src/update/index_documents/extract/extract_word_docids.rs
milli/src/update/index_documents/extract/mod.rs
milli/src/update/index_documents/helpers/grenad_helpers.rs
milli/src/update/index_documents/helpers/mod.rs
milli/src/update/index_documents/mod.rs
milli/src/update/index_documents/typed_chunk.rs
milli/src/update/settings.rs
milli/src/update/word_prefix_docids.rs
milli/tests/search/query_criteria.rs
milli/tests/search/typo_tolerance.rs

Disable typo on attribute

---

cli/Cargo.toml
helpers/Cargo.toml
http-ui/Cargo.toml
infos/Cargo.toml
milli/Cargo.toml

v0.25.0 will be released once #478 is merged

Update version (v0.25.0)

---

cli/Cargo.toml
helpers/Cargo.toml
http-ui/Cargo.toml
infos/Cargo.toml
milli/Cargo.toml

Update version (v0.26.0)

---

bors.toml

Should prevent this problem: https://github.com/meilisearch/milli/pull/489#issuecomment-1094988060

Add the new `Specify breaking` check to bors.toml

---

cli/Cargo.toml
helpers/Cargo.toml
http-ui/Cargo.toml
infos/Cargo.toml
milli/Cargo.toml

No breaking planned in this next release

Update version for the next release (v0.26.1)

---

milli/src/update/settings.rs

Normalize the exact words, as specified in the specification.

normalize exact words

---

CONTRIBUTING.md
README.md

- Add the new CONTRIBUTING.md, highly based on the same guideline as the Meilisearch and Tokenizer ones.
- The "Development Workflow" section is WIP and should be improved but not in this PR. (I will open an issue once it's merge). However, if you see wrong information, please correct them 😇 
- I also updated the README accordingly. The README is the "What is it?" and the "How to use the library? (for the users, not the contributor/maintainers)" documentation. The CONTRIBUTING is the "How to contribute/maintain the repo?" documentation, so mostly for the core team and for every contributor. I will open an issue too once this PR is merged.

First version of new CONTRIBUTING.md

---

flatten-serde-json/fuzz/Cargo.toml
flatten-serde-json/fuzz/fuzz_targets/flatten.rs

This somehow ensure that both crates works correctly together

Improve the fuzzer of the flatten crate

---

milli/src/search/query_tree.rs

fix cargo warnings

---

benchmarks/benches/indexing.rs
benchmarks/build.rs

Add benchmark on nested fields

---

CONTRIBUTING.md

Everything was good in the _Development Workflow_ section so I removed the _WIP Section_ part, now this PR fixes https://github.com/meilisearch/milli/issues/513.

Remove the wip section part of the contributing file

---

milli/src/index.rs
milli/src/update/index_documents/mod.rs
milli/src/update/settings.rs

I made the PR based on release-v0.26.4, but I guess we don't want to merge it on this branch and instead update it to v0.26.5? :thinking:

fix the searchable fields bug when a field is nested

---

milli/src/search/matches/mod.rs

Theses Implementations are needed in meilisearch

Add some implementation on MatchBounds

---

benchmarks/benches/formatting.rs
http-ui/src/main.rs
milli/Cargo.toml
milli/src/lib.rs
milli/src/search/matches/matching_words.rs
milli/src/search/matches/mod.rs
milli/src/search/mod.rs
milli/src/search/query_tree.rs
milli/src/update/index_documents/extract/extract_docid_word_positions.rs
milli/src/update/settings.rs

related to https://github.com/meilisearch/meilisearch/issues/2375
related to https://github.com/meilisearch/meilisearch/issues/2144
related to https://github.com/meilisearch/meilisearch/issues/2417

Integrate charabia

---

milli/src/update/index_documents/mod.rs
milli/src/update/index_documents/transform.rs

Fix https://github.com/meilisearch/meilisearch/issues/2470

Fix wrong internal ids assignments

---

benchmarks/Cargo.toml
cli/Cargo.toml
filter-parser/Cargo.toml
flatten-serde-json/Cargo.toml
helpers/Cargo.toml
http-ui/Cargo.toml
infos/Cargo.toml
json-depth-checker/Cargo.toml
milli/Cargo.toml

A new milli version will be released once this PR is merged https://github.com/meilisearch/milli/pull/543

Update version for next release (v0.29.1)

---

milli/src/index.rs
milli/src/lib.rs
milli/src/search/facet/facet_distribution.rs
milli/src/search/facet/mod.rs
milli/src/search/mod.rs
milli/src/update/settings.rs

This PR adds two new settings in the database, those settings are described [in this spec](https://github.com/meilisearch/specifications/pull/157).

Add the two new pagination and faceting settings

---

milli/Cargo.toml

Bump charabia

---

milli/src/search/matches/mod.rs

Enhance explanation around smart crop algorithms

Chores: Enhance smart-crop code comments

---

benchmarks/build.rs

Downloading the benchmarks datasets is failing [more and more](https://github.com/meilisearch/milli/pull/607#pullrequestreview-1076023074) often; thus, instead of fixing the issue, I thought we could retry multiple times.

Retry downloading the benchmarks datasets

---

http-ui/Cargo.toml
http-ui/src/main.rs
milli/Cargo.toml

- Update `log`
- Upgrade `charabia`
related to https://github.com/meilisearch/meilisearch/issues/2686

Upgrade charabia v0.6.0

---

benchmarks/Cargo.toml
cli/Cargo.toml
filter-parser/Cargo.toml
flatten-serde-json/Cargo.toml
helpers/Cargo.toml
http-ui/Cargo.toml
infos/Cargo.toml
json-depth-checker/Cargo.toml
milli/Cargo.toml

Update version for next release (v0.33.1) in Cargo.toml

---

benchmarks/Cargo.toml
cli/Cargo.toml
filter-parser/Cargo.toml
flatten-serde-json/Cargo.toml
helpers/Cargo.toml
http-ui/Cargo.toml
infos/Cargo.toml
json-depth-checker/Cargo.toml
milli/Cargo.toml
milli/src/search/query_tree.rs

related to https://github.com/meilisearch/meilisearch/issues/2722
- fix the word strategy bug
- update milli version to v0.33.2

Fix word criterion

---

.github/workflows/update-cargo-toml-version.yml

These fixes are minor, and do not prevent us to use the current CI

Minor fixes in the just added update-version CI

---

milli/src/update/index_documents/extract/extract_docid_word_positions.rs
milli/src/update/index_documents/helpers/mod.rs
milli/src/update/index_documents/mod.rs

This PR is related to https://github.com/meilisearch/meilisearch/issues/2743 and is fixing it.

Make sure that long words are ignored

---

README.md

Fixes #652
- Changes spellings of `au{hor` to `author`
- Minor formatting changes in Markdown

Fix #652 - Change Spelling of `author` in `README.md`

---

milli/src/update/index_documents/extract/extract_geo_points.rs

Add missing logging timer to extractors

---

benchmarks/Cargo.toml
cli/Cargo.toml
cli/src/main.rs
filter-parser/Cargo.toml
flatten-serde-json/Cargo.toml
json-depth-checker/Cargo.toml
milli/Cargo.toml

Upgrade all dependencies to their latest versions.
Partly fixes https://github.com/meilisearch/meilisearch/issues/2822

Upgrade all dependencies

---

milli/Cargo.toml
milli/src/heed_codec/mod.rs
milli/src/heed_codec/script_language_codec.rs
milli/src/index.rs
milli/src/update/clear_documents.rs
milli/src/update/delete_documents.rs
milli/src/update/index_documents/extract/extract_docid_word_positions.rs
milli/src/update/index_documents/extract/mod.rs
milli/src/update/index_documents/mod.rs
milli/src/update/index_documents/typed_chunk.rs

Fixes #[646](https://github.com/meilisearch/milli/issues/646)

Store detected language per document during indexing

---

milli/src/index.rs

This functionality is needed to implement the import of dumps correctly.

Add method to create a new Index with specific creation dates

---

.github/workflows/rust.yml
bors.toml
milli/src/search/criteria/mod.rs
milli/src/search/criteria/proximity.rs
milli/src/search/matches/matching_words.rs
milli/src/search/query_tree.rs
milli/src/update/facet/incremental.rs
milli/src/update/index_documents/extract/extract_docid_word_positions.rs
milli/src/update/index_documents/extract/extract_facet_string_docids.rs
milli/src/update/index_documents/extract/extract_word_pair_proximity_docids.rs
milli/src/update/index_documents/extract/extract_word_position_docids.rs
milli/src/update/index_documents/transform.rs
milli/src/update/words_prefixes_fst.rs

Fixes #231 
- fix some clippy errors remain
- add clippy job to CI (I set `nightly` as toolchain)

Add clippy job

---

benchmarks/Cargo.toml
cli/Cargo.toml
filter-parser/Cargo.toml
flatten-serde-json/Cargo.toml
helpers/Cargo.toml
http-ui/Cargo.toml
infos/Cargo.toml
json-depth-checker/Cargo.toml
milli/Cargo.toml
milli/src/update/index_documents/transform.rs
milli/src/update/settings.rs

This PR is a cherry-pick of https://github.com/meilisearch/milli/pull/690 and bumps the crates version to v0.33.5.

Fix soft deleted bug settings

---

.github/workflows/manual_benchmarks.yml
.github/workflows/push_benchmarks_indexing.yml
.github/workflows/push_benchmarks_search_geo.yml
.github/workflows/push_benchmarks_search_songs.yml
.github/workflows/push_benchmarks_search_wiki.yml
.github/workflows/update-cargo-toml-version.yml

ci: Use pre-compiled binaries for faster CI

---

.github/workflows/manual_benchmarks.yml
.github/workflows/push_benchmarks_indexing.yml
.github/workflows/push_benchmarks_search_geo.yml
.github/workflows/push_benchmarks_search_songs.yml
.github/workflows/push_benchmarks_search_wiki.yml

Fixes #714 
Tested with our actions: https://github.com/meilisearch/milli/actions/runs/3591527753/jobs/6046157141

Fix benchmark CI

---

milli/tests/search/distinct.rs

Add test reproducing the bug fixed by #737

---

milli/src/index.rs
milli/src/search/criteria/typo.rs
milli/src/search/criteria/words.rs
milli/src/update/delete_documents.rs
milli/src/update/index_documents/mod.rs

Integrate #734 and #737 into the `release-v0.37.3` branch to avoid to release on `main`
<s>Wait for https://github.com/meilisearch/meilisearch/issues/3235 investigation without merging this PR. Indeed, if a bug fix on milli's side, we might wait for it before merging this PR/</s> -> no need to wait, not a bug

Cherry pick bug fixes for v0.37.3

---

milli/src/error.rs

Milli part of https://github.com/meilisearch/meilisearch/issues/3301
- Change error message strings

Change primary key inference error messages

---

milli/src/error.rs
milli/src/search/facet/facet_distribution.rs

Related to https://github.com/meilisearch/meilisearch/issues/3390
- Title

Indicate filterable attributes when the user sets a non filterable attribute in facet distributions

---

milli/Cargo.toml

related to https://github.com/meilisearch/meilisearch/issues/3391

Update deserr v0.3.0
