meilisearch/milli

milli/src/update/index_documents/transform.rs
Primary key not being present in the `FieldMap` used to cause a panic, which was problematic when we tried to set the primary key through the first document addition. Instead, if the primary key is not present in the map, it is inserted.
The test that checked that the panic occured has been removed.
=> add primary key to fields_id_map when not present

milli/src/update/settings.rs
It fixes the CI of #101.
This PR fixes a spurious test of the settings updates that were sometimes failing because it searched in all the documents' attributes and was expected to find one document on the three provided but was sometimes finding two or three of those. It was because ids were autogenerated (UUID-v4), and those documents ids were containing the searched string of the test. This PR fixes this test by providing the ids directly.
=> Fix the searchable settings test

milli/src/criterion.rs
Implement `Display` for `Criterion`.
Needed to return the criterion with the correct formating to the user.
=> implement display for criterion

milli/src/search/criteria/asc_desc.rs, milli/src/search/criteria/mod.rs
This PR changes:
- The debug prints to show the name of the ascending/descending field.
- Reworked the criteria to makes good use of the facet iterators.
Now instead of going through the whole list of facet values to reach the first candidates according to the facet and order, it keeps the iterator between iterations and pops from it every time until it becomes empty, that's much better 🎉
=> Improve the Asc/Desc criteria

Cargo.lock, milli/Cargo.toml, milli/src/search/criteria/asc_desc.rs, milli/src/search/criteria/fetcher.rs, milli/src/search/criteria/mod.rs, milli/src/search/criteria/proximity.rs, milli/src/search/criteria/typo.rs, milli/src/search/criteria/words.rs, milli/src/search/mod.rs
This PR introduces an alternative way to sort documents based on the proximity between the query words. It uses an iterative algorithm that fetches the word positions in all the candidate documents and does a simple sort on them by using [a plane sweep algorithm](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.26.3610&rep=rep1&type=pdf).
=> Plane-Sweep proximity

infos/src/main.rs
Introduce some missing internal database names in the infos crate and improve the display of the database sizes.
=> Add missing databases to the infos subcommand

milli/src/search/criteria/asc_desc.rs, milli/src/search/criteria/fetcher.rs, milli/src/search/criteria/mod.rs, milli/src/search/criteria/proximity.rs, milli/src/search/criteria/typo.rs, milli/src/search/criteria/words.rs, milli/src/search/mod.rs
This PR changes the words criterion to avoid computing the candidate, it now directly gives the query tree to its child. It also introduces a new way of fetching words derivations in the proximity criterion when the number of candidates is small reducing some queries from 1.2s to 144ms 🎉
=> Optimize the words criterion

Cargo.lock, milli/Cargo.toml, milli/src/index.rs, milli/src/update/clear_documents.rs, milli/src/update/delete_documents.rs, milli/src/update/facets.rs, milli/src/update/index_documents/mod.rs, milli/src/update/settings.rs, milli/src/update/words_prefixes.rs
add the creation date and update date in the index. It is very cumbersome to deal with it on the client side.
I have made the choice to udpate the `updated_at` time before the udpate is executed, to make sure it is called unconditionally, even in case of short-circuiting paths.
Added an update on `put_primary_key` too.
=> add index metadata

milli/src/search/mod.rs
Fix broken offset. 'skip' was used instead of `take` on the candidate iterator, so `for_each` would consume all of the iterator, instead of only the `offset` first.
fix https://github.com/meilisearch/transplant/issues/82
=> fix broken offset

Cargo.lock, http-ui/Cargo.toml, http-ui/src/main.rs, milli/src/update/mod.rs, milli/src/update/settings.rs
This PR introduces a new `Setting` enum that replaces the previous idea of storing user settings as nested `Option`s. It improves readability and decreases chance of misunderstading of what's going on with `Option`s.
| Before | After | Description |
| - | - | - |
| `Some(Some(VALUE))`  | `Setting::Set(VALUE)`  | User set the value |
| `Some(None)`  | `Setting::Reset`  | User reset the value manually |
| `None`  | `Setting::NotSet`  | User didn't set a value |
=> refactor(http, update): introduce setting enum

Cargo.lock, http-ui/Cargo.toml, http-ui/src/main.rs
Test doesn't pass after merging https://github.com/meilisearch/milli/pull/148
```console
➜ http-ui (main) ✗ cargo test                                
Compiling http-ui v0.1.0 (/Users/shekhirin/Projects/milli/http-ui)
Finished test [unoptimized + debuginfo] target(s) in 3.35s
Running /Users/shekhirin/Projects/milli/target/debug/deps/http_ui-462c80964d4c5a0b
running 2 tests
test tests::deserialize_settings ... ok
test tests::serialize_settings ... FAILED
failures:
---- tests::serialize_settings stdout ----
thread 'tests::serialize_settings' panicked at 'expected Token::Struct { name: "Settings", len: 3 } but serialized as Struct { name: "Settings", len: 2, }', /Users/shekhirin/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_test-1.0.125/src/ser.rs:280:9
note: run with …
```
=> test(http): fix and refactor settings assert_(ser|de)_tokens

.github/release-draft-template.yml, .github/workflows/release-drafter.yml
3 rules:
- if you don't want a PR to appear in the release (ex: a typo fix), add the label `skip-changelog` to the PR
- if the PR involves breaking changes, add the `breaking-change` label to the PR -> the minor version (because we are currently in v0.X.Y) will be automatically increased and the PR title will be put in the "Breaking Changes" section of the release description
- to do a release, just create a release in the `Release` section in GitHub (don't push any tag)
And of course, the secret `RELEASE_DRAFTER_TOKEN` is added to the repo
=> Add release drafter files

Cargo.lock, http-ui/Cargo.toml, milli/Cargo.toml
https://github.com/meilisearch/Tokenizer/releases/tag/v0.2.1
=> Update Tokenizer version to v0.2.1

http-ui/src/main.rs, milli/src/index.rs, milli/src/search/query_tree.rs, milli/src/update/settings.rs
Resolves https://github.com/meilisearch/milli/issues/144
---
First implementation, need to find a better way to store synonyms in future.
```console
➜ milli (shekhirin/synonyms) ✗ curl -H 'Content-Type: application/json' -d '{"synonyms": { "NYC": [ "New York", "New York City" ], "New York": [ "NYC", "New York City" ], "New York City": [ "NYC", "New York" ] }}' 127.0.0.1:9700/settings
➜ milli (shekhirin/synonyms) ✗ curl -H 'Content-Type: application/json' -d '{ "query": "" }' 127.0.0.1:9700/query | jq
{
"documents": [
{
"city": "New York",
"id": "15c403fa-b658-490a-ad07-1c9e41b7fd41",
"country": "USA"
},
{
"city": "Moscow",
"id": "46abe926-5da0-4e11-b9a5-3496da077126",
"country": "Russia"
},
{
"city": "Paris",
"id": "d3533315-1272-412a-84f1-cbeaf462e094",
"country": "France"
}
], …
```
=> Support synonyms

README.md
Fix https://github.com/meilisearch/milli/issues/175
=> do not use echo that espaces newline

milli/src/search/criteria/asc_desc.rs, milli/src/search/criteria/attribute.rs, milli/src/search/criteria/final.rs, milli/src/search/criteria/initial.rs, milli/src/search/criteria/mod.rs, milli/src/search/criteria/proximity.rs, milli/src/search/criteria/typo.rs, milli/src/search/criteria/words.rs, milli/src/search/mod.rs
- pass excluded document to criteria to remove them in higher levels of the bucket-sort
- merge already returned document with excluded documents to avoid duplicas
Related to #125 and #112
Fix #170
=> Remove excluded document in criteria iterations

milli/src/update/index_documents/mod.rs
The `nb_document` needs to be public to allow the conversion of update statuses to the legacy meilisearch format.
=> make document addition number visible

milli/src/index.rs, milli/src/update/index_documents/transform.rs
Resolves https://github.com/meilisearch/milli/issues/174
The problem was with calculation of fields distribution before the merge in `output_from_sorter()`. So if you'd import two documents with the same primary key value, fields distribution will count it as two documents, while `output_from_sorter()` will merge these documents into one.
---
```console
➜ Downloads cat short_movies.json
[
{"id":"47474","title":"The Serpent's Egg","poster":"https://image.tmdb.org/t/p/w500/n7z0doFkXHcvo8QQWHLFnkEPXRU.jpg","overview":"The Serpent's Egg follows a week in the life of Abel Rosenberg, an out-of-work American circus acrobat living in poverty-stricken Berlin following Germany's defeat in World War I.","release_date":246844800,"genres":["Thriller","Drama","Mystery"]},
{"id":"47474","title":"The …
```
=> Fix fields distribution after documents merge

milli/src/fields_ids_map.rs, milli/src/search/criteria/exactness.rs, milli/src/search/criteria/mod.rs, milli/src/search/mod.rs, milli/src/search/query_tree.rs
=> Exactness criterion

milli/src/search/criteria/asc_desc.rs, milli/src/search/criteria/attribute.rs, milli/src/search/criteria/exactness.rs, milli/src/search/criteria/final.rs, milli/src/search/criteria/initial.rs, milli/src/search/criteria/mod.rs, milli/src/search/criteria/proximity.rs, milli/src/search/criteria/typo.rs, milli/src/search/criteria/words.rs, milli/src/search/query_tree.rs
Before the bucket candidates were the result of the facet filters or result of the query tree.
They will now be only the result of the query tree, making the number of candidates more consistent between the same request with or without facet filters.
Fix some clippy warnings.
Fix #186
=> Make bucket candidates optionals

http-ui/src/main.rs, infos/src/main.rs, milli/src/criterion.rs, milli/src/index.rs, milli/src/search/criteria/asc_desc.rs, milli/src/search/distinct/facet_distinct.rs, milli/src/search/distinct/map_distinct.rs, milli/src/search/distinct/mod.rs, milli/src/search/facet/facet_condition.rs, milli/src/search/facet/facet_distribution.rs, milli/src/search/facet/mod.rs, milli/src/search/mod.rs, milli/src/update/clear_documents.rs, milli/src/update/delete_documents.rs, milli/src/update/facets.rs, milli/src/update/index_documents/mod.rs, milli/src/update/index_documents/store.rs, milli/src/update/settings.rs
This pull request is related to https://github.com/meilisearch/milli/issues/152 and changes the layout of the facets values, numbers and strings are now in dedicated databases and the user no more needs to define the type of the fields. No more conversion between the two types is done, numbers (floats and integers converted to f64) go to the facet float database and strings go to the strings facet database.
There is one related issue that I found regarding CSVs, the values in a CSV are always considered to be strings, [meilisearch/specifications#28](https://github.com/meilisearch/specifications/blob/d916b57d748628c3b45500e9dfa46b50dfa2ad3f/text/0028-indexing-csv.md) fixes this issue by allowing the user to define the fields types using `:` in the "CSV Formatting Rules" section.
All …
=> Transfer numbers and strings facets into the appropriate facet databases

milli/src/heed_codec/roaring_bitmap/bo_roaring_bitmap_codec.rs
Optimize the `BoRoaringBitmapCodec` by preventing it from emiting useless error that caused allocation. On my flamegraph, the byte_decode function went from 4.13% to  1.70% (of transplant graph).
This may not be the greatest optimization ever, but hey, this was a low hanging fruit.
before:
after:
=> Optimize roaring codec

infos/src/main.rs, milli/src/heed_codec/field_id_word_count_codec.rs, milli/src/heed_codec/mod.rs, milli/src/index.rs, milli/src/lib.rs, milli/src/search/criteria/exactness.rs, milli/src/search/criteria/mod.rs, milli/src/update/clear_documents.rs, milli/src/update/delete_documents.rs, milli/src/update/index_documents/merge_function.rs, milli/src/update/index_documents/mod.rs, milli/src/update/index_documents/store.rs
This PR introduces a new database, `field_id_word_count_docids`, that maps the number of words in an attribute with a list of document ids. This relation is limited to attributes that contain less than 11 words.
This database is used by the exactness criterion to know if a document has an attribute that contains exactly the query without any additional word.
Fix #165 
Fix #196
Related to [specifications:#36](https://github.com/meilisearch/specifications/pull/36)
=> Add field id word count docids database

milli/src/update/index_documents/mod.rs, milli/src/update/index_documents/transform.rs
this pr:
- Adds early returns on empty document additions, avoiding error messages to be returned when adding no documents and no primary key was set.
- Changes the primary key inference logic to match that of legacy meilisearch.
close #194
=> Fix primary key behavior

Cargo.lock, benchmarks/Cargo.toml, benchmarks/benches/utils.rs, benchmarks/scripts/compare.sh
The benchmarks compare script was not using the `--output` flag and was therefore failing the download of the JSON reports. We also modified the criterion benchmarks to use shorter names, it helps in looking at the benchmarks in the terminal.
=> Fix the benchmarks script and names

benchmarks/README.md
- Move the Dataset part to the end of the readme so when peoples just want to run the benchmarks they are not tempted to download the benchmarks by hand (which are going to be downloaded anyway by the `build.rs` script)
- Fix the links in the dataset -- wiki part
=> Improve the benchmarks readme

milli/src/criterion.rs, milli/src/update/settings.rs
We now make sure that we insert the new field name into the fields-ids-map when we are creating and modifying the criteria. Previously the engine was throwing an error due to that if the field was missing in the fields ids map.
=> Save the criteria field name in the fields ids map

milli/src/search/query_tree.rs
hard separators will now split a phrase query as two sequential phrases (double-quoted strings):
the query `"Radioactive (Imagine Dragons)"` would be considered equivalent to `"Radioactive" "Imagine Dragons"` which as the little disadvantage of not keeping the order of the two (or more) separate phrases.
Fix #208
=> Make hard separators split phrase query

milli/src/search/criteria/attribute.rs, milli/src/search/criteria/mod.rs, milli/src/search/criteria/proximity.rs, milli/src/search/criteria/typo.rs, milli/src/search/matching_words.rs, milli/src/search/query_tree.rs
Replace `Consecutive` by `Phrase` in the query tree in order to remove theoretical bugs,
due to the `Consecutive` enum type.
=> Replace Consecutive by Phrase in query tree

Cargo.toml
compiling tests in release takes too much time.
Reverts meilisearch/milli#224
Fix #233
=> Revert "Enable optimization in every profile"

milli/src/lib.rs
re-export sub-error types so they can be matched upon outside of milli.
=> change sub errors visibility

milli/src/error.rs, milli/src/update/index_documents/transform.rs
We were wrongly returning a `MissingPrimaryKey` instead of a `MissingDocumentId` error for when a document was missing a document id. We also improved the error message for when a document id is invalid (wrong type or wrong format).
=> Return a `MissingDocumentId` error when a document doesn't have one

milli/src/search/mod.rs
There was no check on the limit and thus if a user specified a very large number this line could cause a panic.
=> Fix the limit

milli/src/error.rs, milli/src/search/facet/facet_distribution.rs
This PR fixes two invalid behaviors and fixes #253:
- We were ignoring the list of fields for which the user wanted a facet distribution.
- We were not raising any error for when a non-filterable field was requested a facet distribution.
~For the latter behavior I need the help of @curquiza to help me choose the right error type.~
=> Fix facet distribution error

milli/src/update/delete_documents.rs, milli/src/update/index_documents/mod.rs
We were incorrectly using LMDB by keeping references into the database while modifying it, it was mostly due to heed not specifying anything about this behavior (blame me). I made sure in this PR that we always keep and **owned** version of the references we were previously using.
This PR partially fixes #261, we need to bump heed to v0.12 when it is available as it marks the `del/put_current`, and `append` methods as unsafe and explains why.
I would like to thank the whole Rust community for their help, especially:
- @Pointerbender 🎸 who [tracked down the exact point where the memory write was altered](https://github.com/meilisearch/milli/issues/261#issuecomment-868983226),
- @Diggsey 💯 who [found, in the LMDB documentation, the sentence that we forgot …
=> Fix the invalid heed usage

Cargo.lock, helpers/Cargo.toml, http-ui/Cargo.toml, infos/Cargo.toml, milli/Cargo.toml, milli/src/update/delete_documents.rs, milli/src/update/index_documents/mod.rs, search/Cargo.toml
By bumping to a new version of heed (from git, v0.12.0 unpublished yet), this PR fixes Windows disk reservation problems. This new version of heed changes the `del/put_current`, and `append` iterator methods signature by declaring them unsafe.
This PR also bumps milli itself into v0.7.0 as it is breaking due to the heed/LMDB bump.
This PR must be merged after #264.
=> Bump LMDB to the latest version (v0.9.70)

milli/src/search/matching_words.rs
closes #262 
I basically rewrote a part of the damerau-levenshtein function we were using for the highlighting to accept at most two errors from the user and stop on the third mistake.
Also, now it supports utf-8, so it should fix our issue.
=> Highlighting

milli/src/external_documents_ids.rs, milli/src/index.rs, milli/src/update/index_documents/mod.rs
This PR fixes #268.
The issue was in the `ExternalDocumentsIds` implementation in the specific case that an external document id was in the soft map marked as deleted.
The bug was due to a wrong assumption on my side about how the FST unions were returning the `IndexedValue`s, I thought the values returned in an array were in the same order as the FSTs given to the `OpBuilder` but in fact, [the `IndexedValue`'s `index` field was here to indicate from which FST the values were coming from](https://docs.rs/fst/0.4.7/fst/map/struct.IndexedValue.html).
=> Fix bug when inserting previously deleted documents

milli/src/search/criteria/mod.rs, milli/src/search/criteria/proximity.rs, milli/src/search/criteria/typo.rs, milli/src/search/distinct/facet_distinct.rs, milli/src/search/facet/facet_distribution.rs, milli/src/search/facet/filter_condition.rs, milli/src/search/facet/mod.rs, milli/src/search/mod.rs, milli/src/update/available_documents_ids.rs, milli/src/update/delete_documents.rs, milli/src/update/facets.rs, milli/src/update/index_documents/merge_function.rs, milli/src/update/index_documents/mod.rs, milli/src/update/words_level_positions.rs
In this PR we are just replacing the usages of the roaring operations function by the new operators. This removes a lot of warnings.
=> Remove the roaring operation functions warnings

http-ui/src/main.rs
This route just `exit` the process. This can come in handy when you run `http-ui` inside of another process (a profiler for example), and you don't want to kill everything
=> [http-ui] Introduce the route `die`

Cargo.lock, benchmarks/Cargo.toml, helpers/Cargo.toml, http-ui/Cargo.toml, infos/Cargo.toml, milli/Cargo.toml, milli/src/index.rs, search/Cargo.toml
We introduced a new flag in our fork of LMDB, this `AlwaysFreePages` flag forces LMDB to always free the single pages it uses before writing to the disk instead of keeping them in a linked list.
Declaring this flag reduces the memory print (leak) we have on memory after indexing a lot of documents.
Fixes #279.
=> Use the AlwaysFreePages flag when opening an index

Cargo.lock, infos/src/main.rs, milli/Cargo.toml, milli/src/heed_codec/facet/facet_level_value_f64_codec.rs, milli/src/heed_codec/facet/facet_value_string_codec.rs, milli/src/heed_codec/facet/field_doc_id_facet_f64_codec.rs, milli/src/heed_codec/facet/field_doc_id_facet_string_codec.rs, milli/src/heed_codec/field_id_word_count_codec.rs, milli/src/heed_codec/obkv_codec.rs, milli/src/index.rs, milli/src/lib.rs, milli/src/search/facet/facet_distribution.rs, milli/src/search/facet/mod.rs, milli/src/update/delete_documents.rs, milli/src/update/facets.rs, milli/src/update/index_documents/merge_function.rs, milli/src/update/index_documents/mod.rs, milli/src/update/index_documents/store.rs, milli/src/update/index_documents/transform.rs
Fixes #248.
In this PR I updated the `obkv` crate, it now supports arbitrary key length and therefore I was able to use an `u16` to represent the fields instead of a single byte. It was impressively easy to update the whole codebase 🍡 🍔
=> Support documents with at most 65536 fields

.github/workflows/benchmarks.yml
This should fix this issue:
https://github.com/meilisearch/milli/runs/3104228432?check_suite_focus=true
I think a real fix would be to fix the configuration of our github runner but I don't know how to do it.
@curquiza could probably help us on that once she's back from vacation :smile:
=> Add a $HOME to the CI

Cargo.lock, milli/Cargo.toml, milli/src/update/delete_documents.rs, milli/src/update/index_documents/mod.rs
Ok, good news, after a little session of debugging with @irevoire we found out that the bug seems to be related to zeroes in the input update. The engine wasn't designed to accept those. The chosen solution is to update the tokenizer to remove those zeroes. We are waiting on https://github.com/meilisearch/tokenizer/pull/52 to be merged and a new version to be released.
It is not an undefined behavior, I repeat: it is a "normal" bug 🎉 👏
----
This PR tries to fix a bug where we use LMDB in the wrong way, leading to panic due to an undefined behavior on the Rust side. I thought [we fixed it in a previous PR](https://github.com/meilisearch/milli/pull/264) but we found out that _a similar_ bug was still present. @bb found a way to trigger this bug and helped us find the origin of it.
As I …
=> Fix a bug about zero bytes in the inputs

milli/src/update/words_level_positions.rs
The prefix search was inverted when we generated the DB.
Instead of searching if word had a prefix in prefix fst,
we were searching if the word was a prefix of a prefix contained in the prefix fst.
The indexer, now, iterate over prefix contained in the fst
and search them by prefix in the word-level-position-docids database,
aggregating matches in a sorter.
Fix #299
=> Fix prefix level position docids database

helpers/Cargo.toml, http-ui/Cargo.toml, infos/Cargo.toml, milli/Cargo.toml, search/Cargo.toml
Updating the minor and not patch since #300 seems to be breaking: it involves a re-indexation to get the fix, so it involves an additional step from the users, not only downloading the latest version.
=> Update milli to v0.9.0

helpers/Cargo.toml, http-ui/Cargo.toml, infos/Cargo.toml, milli/Cargo.toml, search/Cargo.toml
Replaces https://github.com/meilisearch/milli/pull/304
=> Update version for the next release (v0.10.0)

http-ui/Cargo.toml, milli/Cargo.toml
Fixes panic when indexing data containing [control characters](https://en.wikipedia.org/wiki/Control_character) but continue accepting whitespace, obviously.
Related to https://github.com/meilisearch/MeiliSearch/issues/1590
=> Update tokenizer version to v0.2.5

milli/src/update/delete_documents.rs
Fixes a bug where the deletion of documents was returning a decoding error. But only when the settings are set with filterable attributes.
This bug was introduced in #254 in which we made the engine faster in returning the facet distribution. We changed the way we were storing the inverted index, we were no more storing only documents ids with the original values but also groups identified with integers, depending on the facet level we were using. This is similar to how facet numbers are already stored.
⚠️ As @curquiza already said, we must first revert #309 before merging this!
Related to https://github.com/meilisearch/MeiliSearch/issues/1601.
=> Fix the facet string docids filterable deletion bug

benchmarks/benches/indexing.rs
There was a panic on the benchmark and while I was trying to understand what was happening I decided to rewrite the way the benchmarks were working.
Before we were creating a database with the good setting, and then for each benchmarks we were:
1. Deleting all documents in the database
2. Indexing a batch of documents
Now for each iteration we recreate entirely a new database from scratch.
Since deleting all the documents in a database may not be the same as starting with a fresh new database I prefer this solution.
=> Rewrite the indexing benchmarks

http-ui/src/main.rs
- Add a `reset_sortable_attribute` method
- Add the `sortable_attributes` to http-ui
- Fix some broken test in http-ui
=> Sortable attributes in http-ui

http-ui/src/main.rs, milli/src/update/settings.rs
I forgot to add the `reset_sortable_fields` method on the `Settings` builder, it is no big deal as the library user (like MeiliSearch) can always call `set_sortable_fields` with an empty list of fields, it is equivalent.
=> Introduce the reset_sortable_fields Settings method

.github/workflows/cron_benchmarks_indexing.yml, .github/workflows/cron_benchmarks_search_songs.yml, .github/workflows/cron_benchmarks_search_wiki.yml
All the benchmarks run every Friday on the `main` branch.
To avoid having pending benchmarks everywhere, we execute one benchmark every 8 hours.
Then the results are uploaded as if it was a normal user-run benchmark.
This PR closes #314 and #321
=> Run all benchmarks once every friday

milli/src/search/mod.rs
Seems like we don't need to retrieve `sortable_fields` from the index if there's no any `sort_criteria` in the query.
Small 🤏  optimization opportunity out there.
=> Get sortable_fields from index only if criteria present in query

milli/src/search/facet/facet_string.rs, milli/tests/search/query_criteria.rs
Resolves https://github.com/meilisearch/milli/issues/333
<details>
<summary>curl checks</summary>
```console
➜  ~ curl -s 'localhost:7700/indexes/movies/search' -d '{"sort": ["title:asc"], "limit": 30}' | jq -r '.hits | map(.title)[]'
#1 Cheerleader Camp
#Horror
#RealityHigh
#Roxy
#SquadGoals
$5 a Day
$9.99
'71
(2)
(500) Days of Summer
(Girl)Friend
*batteries not included
...And God Created Woman
...And Justice for All
...E fuori nevica!
.45
1
1 Mile To You
1 Night
10
10 Cloverfield Lane
10 giorni senza mamma
10 Items or Less
10 Rillington Place
10 Rules for Sleeping Around
10 Things I Hate About You
10 to Midnight
10 Years
10,000 BC
10,000 Saints
➜  ~ curl -s 'localhost:7700/indexes/movies/search' -d '{"sort": ["title:desc"], "limit": 30}' | jq -r '.hits | map(.title)[]'
크게 될 놈
왓칭
뷰티플 …
```
=> Fix string fields sorting

milli/Cargo.toml
Milli is not using any of grenad default features, and it's zstd feature creates conflict with meilisearch. This pr simply remove the unused features.
=> remove unused grenad default features

milli/src/error.rs, milli/src/search/mod.rs, milli/tests/search/mod.rs, milli/tests/search/sort.rs
This PR makes the engine throw an error for when the ranking rules don't contain the `sort` rule, the `sortable_fields` are correctly set but the user tries to use the `sort` query parameter. Doing so will have no effect on the returned documents so we preferred returning an error to help debug this.
That's breaking on the MeiliSearch side as we added a new variant to the `UserError` enum.
=> Throw a query time error when a sort parameter is used but the sort ranking rule is missing

milli/src/criterion.rs
This PR moves the sort ranking rule at the 5th position by default, right before the exactness one.
=> Move the sort ranking rule before the exactness ranking rule

http-ui/src/main.rs, milli/Cargo.toml
This PR enables the grenad `tempfile` feature back, [when this is feature is disabled the sorter writes the entries in memory](https://github.com/Kerollmops/grenad/blob/7c082d05bf3fe88c4e66a8104e4f01229fb12c67/src/sorter.rs#L470-L476) instead of on disk and therefore, consumes more memory. By enabling this feature grenad merges on disk by using the `tempfile` dependency.
This PR also bumps milli to v0.3.1 where @ManyTheFish added an assert for when the allocator can't allocate and disable the default snappy compression in the `http-ui` crate.
=> Enable the grenad tempfile feature back

milli/src/criterion.rs, milli/src/error.rs
This is one possible fix for #339 
We would then need to patch these lines https://github.com/meilisearch/MeiliSearch/blob/main/meilisearch-http/src/index/search.rs#L110-L114 to return the error we want.
Another solution would be to add a parameter to the `from_str` to specify which context we are in.
=> Let the caller decide what kind of error they want to returns when parsing `AscDesc`

.github/workflows/benchmarks.yml, benchmarks/Cargo.toml, benchmarks/README.md, benchmarks/benches/indexing.rs, benchmarks/benches/search_geo.rs, benchmarks/benches/utils.rs, benchmarks/build.rs
closes #336
Should I merge this PR in #322 and then we merge everything in `main` or should we wait for #322 to be merged and then merge this one in `main` later?
=> Add benchmarks for the geosearch

milli/src/criterion.rs
With my previous PR on the geosearch I erased the change I've introduced with my pre-previous PR about the new error type when we fail to parse the `AscDesc` type.
Sorry for that, here is the fix
=> Fix the returned `AscDesc` error

.github/workflows/rust.yml, benchmarks/Cargo.toml, benchmarks/benches/indexing.rs, benchmarks/benches/search_geo.rs, benchmarks/benches/utils.rs
#324 broke all benchmarks.
I fixed everything and noticed that `cargo check --all` was insufficient to check the bench in multiple workspaces, so I also updated the CI to use `cargo check --workspace --all-targets`.
=> Fix all the benchmarks 

milli/src/update/index_documents/mod.rs
We made several indexing tests using different sizes of datasets (5 datasets from 9MiB to 100MiB) on several typologies of VMs (`XS: 1GiB RAM, 1 VCPU`, `S: 2GiB RAM, 2 VCPU`, `M: 4GiB RAM, 3 VCPU`, `L: 8GiB RAM, 4 VCPU`).
The result of these tests shows that the `4MiB` chunk size seems to be the best size compared to other chunk sizes (`2Mib`, `4MiB`, `8Mib`, `16Mib`,  `32Mib`, `64Mib`, `128Mib`).
below is the average time per chunk size:
<details>
<summary>Detailled data</summary>
<br>
</br>
</details>
=> Change chunk size to 4MiB to fit more the end user usage

http-ui/src/main.rs, milli/src/asc_desc.rs, milli/src/error.rs, milli/src/lib.rs
This PR simplify the error handling of asc-desc rules for Meilisearch or any other wrapper by providing directly in milli a new error type called `SortError` that can be generated from an `AscDescError` and that can be automatically converted to a `UserError`.
Basically now, wherever you are in the code as a user or in milli you can parse an `AscDesc` syntax and depending on the context, cast it either as a `SortError` or a `CriterionError` in one line with improved error messages.
=> Provide a sort error handler

milli/src/search/query_tree.rs, milli/src/update/index_documents/mod.rs
The bug comes from the typo tolerance, to know how many typos are accepted we were counting bytes instead of characters in a word.
On Chinese Script characters, we were allowing  2 typos on 3 characters words.
We are now counting the number of char instead of counting bytes to assign the typo tolerance.
Related to [Meilisearch#1714](https://github.com/meilisearch/MeiliSearch/issues/1714)
=> Fix Meilisearch 1714

milli/src/update/index_documents/mod.rs, milli/src/update/index_documents/transform.rs
When a docid is an integer, we stop casting it to a string, and thus we don't add `"` around it.
=> Stop casting integer docids to string

benchmarks/benches/utils.rs, http-ui/src/documents_from_csv.rs, http-ui/src/main.rs
Benchmarks on `search_songs` were crashing because of the CSV parsing.
=> Enhance CSV document parsing

milli/src/search/criteria/attribute.rs
This PR contains an ugly quick fix of [meilisearch#1707](https://github.com/meilisearch/MeiliSearch/issues/1707).
- remove comparison reverse on rank. Enhancing relevancy and performances
- iterate over level 0 only. Enhancing performances.
A better fix is in development.
=> Hotfix meilisearch#1707

benchmarks/benches/indexing.rs, benchmarks/benches/utils.rs, cli/src/main.rs, http-ui/src/main.rs, milli/src/index.rs, milli/src/search/distinct/mod.rs, milli/src/search/facet/filter.rs, milli/src/update/clear_documents.rs, milli/src/update/delete_documents.rs, milli/src/update/facets.rs, milli/src/update/index_documents/mod.rs, milli/src/update/settings.rs, milli/src/update/update_builder.rs, milli/src/update/words_prefixes_fst.rs, milli/tests/search/distinct.rs, milli/tests/search/mod.rs, milli/tests/search/query_criteria.rs
Removing the `update_id` from `UpdateBuidler`, since it serves no purpose. I had introduced it when working in HA some time ago, but I think there are better ways to do it now, so it can be removed an stop being in our way.
=> remove update_id in UpdateBuilder

http-ui/Cargo.toml, milli/Cargo.toml, milli/src/lib.rs
- Update tokenizer v0.2.6
- Export tokenizer from milli in order to use the same version between milli and Meilisearch
=> Update tokenizer v0.2.6

milli/src/update/mod.rs
Change the visibility of `DocumentDeletionResult`, so its fields can be accesses from outside milli.
=> change visibility of DocumentDeletionResult

milli/src/update/index_documents/extract/extract_word_pair_proximity_docids.rs
Sort positions before iterating over them during word pair proximity extraction.
fixes [Meilisearch#1913](https://github.com/meilisearch/MeiliSearch/issues/1913)
=>  fix word pair proximity indexing

filter-parser/src/lib.rs, milli/src/search/facet/filter.rs
This PR introduces the depth method on the FilterCondition type to be able to react to it. It is meant to be used to reject filters that go too deep and can make the engine stack overflow.
=> Introduce the depth method on FilterCondition

benchmarks/benches/utils.rs, cli/src/main.rs, filter-parser/src/lib.rs, http-ui/src/main.rs, milli/src/search/facet/filter.rs, milli/src/update/delete_documents.rs, milli/src/update/settings.rs
This PR is related to the issue comment https://github.com/meilisearch/MeiliSearch/issues/1338#issuecomment-989322889 which exhibits the fact that when a filter is known to be empty no results are returned which is wrong, the filter should not apply as no restriction is done on the documents set.
The filter system on the milli side has introduced an Empty state which was used in this kind of situation but I found out that it is not needed and that when we parse a filter and that it is empty we can simply return `None` as the `Filter::from_array` constructor does. So I removed it and added tests!
On the MeiliSearch side, we just need to match on a `None` and completely ignore the filter in such a case.
=> Prefer returning `None` instead of using an `FilterCondition::Empty` state

.github/workflows/manual_benchmarks.yml, .github/workflows/push_benchmarks_indexing.yml, .github/workflows/push_benchmarks_search_geo.yml, .github/workflows/push_benchmarks_search_songs.yml, .github/workflows/push_benchmarks_search_wiki.yml
Since we now have multiple self-hosted github runners, we need to differentiate them calling them in the CI. The `self-hosted` label is the default one, so we need to use the unique and appropriate one for the benchmark machine
=> Benchmark CIs: not use a default label to call the GH runner

milli/src/lib.rs, milli/src/search/criteria/geo.rs, milli/src/search/facet/filter.rs, milli/src/update/delete_documents.rs, milli/src/update/index_documents/typed_chunk.rs
Related to this issue: https://github.com/meilisearch/MeiliSearch/issues/1872
Fix the whole computation of distance for any “geo” operations (sort or filter). Now when you sort points they are returned to you in the right order.
And when you filter on a specific radius you only get points included in the radius.
This PR changes the way we store the geo points in the RTree.
Instead of considering the latitude and longitude as orthogonal coordinates, we convert them to real orthogonal coordinates projected on a sphere with a radius of 1.
This is the conversion formulae.
Which, in rust, translate to this function:
```rust
pub fn lat_lng_to_xyz(coord: &[f64; 2]) -> [f64; 3] {
let [lat, lng] = coord.map(|f| f.to_radians());
let x = lat.cos() * lng.cos();
let y = lat.cos() * lng.sin();
let z = …
```
=> Store the geopoint in three dimensions

http-ui/Cargo.toml, http-ui/src/main.rs, milli/Cargo.toml, milli/src/search/matching_words.rs
Fixes https://github.com/meilisearch/MeiliSearch/issues/1480
The `matching_bytes` function takes a `&Token` now and:
- gets the number of bytes to highlight (unchanged).
- uses `Token.num_graphemes_from_bytes` to get the number of grapheme clusters to highlight.
In essence, the `matching_bytes` function now returns the number of matching grapheme clusters instead of bytes.
Added proper highlighting in the HTTP UI:
- requires dependency on `unicode-segmentation` to extract grapheme clusters from tokens
- `<mark>` tag is put around only the matched part
- before this change, the entire word was highlighted even if only a part of it matched
Since `matching_bytes` does not return number of bytes but grapheme clusters, should it be …
=> Fix search highlight for non-unicode chars

milli/src/search/facet/filter.rs
- Stop lowercasing the field when looking in the field id map
- When a field id does not exist it means there is currently zero
documents containing this field thus we return an empty RoaringBitmap
instead of throwing an internal error
Will fix https://github.com/meilisearch/MeiliSearch/issues/2082 once meilisearch is released
=> fix(filter): Fix two bugs.

cli/Cargo.toml, helpers/Cargo.toml, http-ui/Cargo.toml, infos/Cargo.toml, milli/Cargo.toml
This is breaking because of this PR:
https://github.com/meilisearch/milli/commit/98a365aaae53e2d543f65f5261811a23dad65660
Should we do a special branch to only release the [patch](https://github.com/meilisearch/milli/pull/433) for https://github.com/meilisearch/MeiliSearch/issues/2082 (which is non-breaking)?
=> bump milli to v0.22.0

cli/src/main.rs
I've made the following changes to the cli:
- `settings-update` become `settings`, with two subcommands: `update` and `show`.
- `document-addition` becomes `documents` with a subcommands: `add` (I'll add a feature to list documents later)
- `search` now has an interactive mode `-i`
- search return the number of documents and the time it took to perform the search.
=> CLI improvements

milli/src/update/word_prefix_pair_proximity_docids.rs
This PR first fixes the algorithm we used to select and compute the word prefix pair proximity database. The previous version was skipping nearly all of the prefixes. The issue is that this fix made this method to take more time and we were trying to reduce the time spent in it.
With @ManyTheFish we found out that we could skip some of the work we were doing by:
- discarding the prefixes that were shorter than a specific threshold (default: 2).
- discarding the word prefix pairs with proximity bigger than a specific threshold (default: 4).
- remove the unused threshold that was specifying a minimum amount of word docids to merge.
We will take more time to do some more optimization, like stop clearing and recomputing from scratch the database, we will compute the subsets of keys to create, …
=> Fix and improve word prefix pair proximity

http-ui/src/main.rs
This PR correctly uses the `BufRead` trait to read every line of the content instead of just the first one. This bug was only affecting the http-ui test crate.
=> Fix the parsing of ndjson requests to index more than the first line

milli/src/documents/builder.rs
This pr allows null values in csv:
- if the field is of type string, then an empty field is considered null (`,,`), anything other is turned into a string (i.e `, ,` is a single whitespace string)
- if the field is of type number, when the trimmed field is empty, we consider the value null (i.e `,,`, `, ,` are both null numbers) otherwise we try to parse the number.
=> allow null values in csv

milli/Cargo.toml, milli/src/index.rs, milli/src/update/clear_documents.rs, milli/src/update/delete_documents.rs, milli/src/update/facets.rs, milli/src/update/settings.rs
We only use `chrono` as a wrapper around `time`, and since there has been an [open CVE on `chrono` for at least 3 months now](https://github.com/chronotope/chrono/pull/632) and the repo seems to be [struggling with maintenance](https://github.com/chronotope/chrono/pull/639), I think we should use `time` directly which is way more active and sufficient for our use case.
EDIT: Actually the CVE status has been known for more than 6 months: https://github.com/chronotope/chrono/issues/602
=> Get rid of chrono in favor of time

milli/Cargo.toml, milli/src/error.rs, milli/src/update/facets.rs, milli/src/update/index_documents/extract/extract_docid_word_positions.rs, milli/src/update/index_documents/extract/extract_facet_number_docids.rs, milli/src/update/index_documents/extract/extract_facet_string_docids.rs, milli/src/update/index_documents/extract/extract_fid_docid_facet_values.rs, milli/src/update/index_documents/extract/extract_fid_word_count_docids.rs, milli/src/update/index_documents/extract/extract_geo_points.rs, milli/src/update/index_documents/extract/extract_word_docids.rs, milli/src/update/index_documents/extract/extract_word_pair_proximity_docids.rs, milli/src/update/index_documents/extract/extract_word_position_docids.rs, milli/src/update/index_documents/extract/mod.rs, milli/src/update/index_documents/helpers/grenad_helpers.rs, milli/src/update/index_documents/helpers/mod.rs, milli/src/update/index_documents/mod.rs, milli/src/update/index_documents/transform.rs, milli/src/update/index_documents/typed_chunk.rs, milli/src/update/word_prefix_docids.rs, milli/src/update/word_prefix_pair_proximity_docids.rs, milli/src/update/words_prefix_position_docids.rs
This PR depends on the fixes done in #431 and must be merged after it.
In this PR we will bring the `WordPrefixPairProximityDocids`, `WordPrefixDocids` and, `WordPrefixPositionDocids` update structures to a new era, a better era, where computing the word prefix pair proximities costs much fewer CPU cycles, an era where this update structure can use the, previously computed, set of new word docids from the newly indexed batch of documents.
---
The `WordPrefixPairProximityDocids` is an update structure, which means that it is an object that we feed with some parameters and which modifies the LMDB database of an index when asked for. This structure specifically computes the list of word prefix pair proximities, which correspond to a list of pairs of words associated with a proximity (the …
=> Speed up the word prefix databases computation time

benchmarks/Cargo.toml, cli/Cargo.toml, helpers/Cargo.toml, http-ui/Cargo.toml, infos/Cargo.toml, milli/Cargo.toml, milli/fuzz/Cargo.toml
Since grenad and heed have been moved to the meilisearch orga, this PR changes the link.
This is a minor change since GitHub handles automatically the redirection. This PR is only for consisitency.
=> Update heed link in cargo toml

milli/src/lib.rs
Fixes the issue in meilisearch https://github.com/meilisearch/meilisearch/issues/2210
=> exporting heed to avoid having different versions of Heed in Meilisearch

milli/src/update/word_prefix_pair_proximity_docids.rs, milli/src/update/words_prefixes_fst.rs
This pr introduces two optimizations that greatly improve the speed of computing prefix databases.
- The time that it takes to create the prefix FST has been divided by 5 by inverting the way we iterated over the words FST.
- We unconditionally and needlessly checked for documents to remove in  `word_prefix_pair`, which caused an iteration over the whole database.
=> optimize prefix database

Cargo.toml
This PR updates the workspace resolver to v2. This should fix [the benchmarks](https://github.com/meilisearch/milli/runs/5558347765?check_suite_focus=true#step:8:184).
=> Set the cargo crate resolver to v2

milli/src/search/facet/filter.rs
Fixes https://github.com/meilisearch/meilisearch/issues/2140
Is there a good way to reduce de duplication here? Maybe adding a shared function? I don't know the best and idiomatic way to do that, I appreciate any tip!
Another doubt is related to the duplication of the calling:
```rs
// filter.rs:373
FilterError::AttributeNotFilterable {
attribute,
filterable: filterable_fields.into_iter().collect::<Vec<_>>().join(" "),
},
```
and
```rs
// filter.rs:424
return Err(point[0].as_external_error(FilterError::AttributeNotFilterable {
attribute: "_geo",
filterable: filterable_fields.into_iter().collect::<Vec<_>>().join(" "),
}))?;
```
I think we could make the `filterable_fields.into_iter().collect::<Vec<_>>().join(" ")` directly into the error handling like the sortable error. I made it into the …
=> Add a new error message when the filterableAttributes are empty

milli/Cargo.toml
Lindera often fails to download some data from google drive we can’t compile consistently meilisearch / milli.
We can’t bump to the latest version (that moved out of google drive) either because lindera uses reqwest with openssl with no way of configuring it our benchmarks were not able to run. The latter issue should be fixed by https://github.com/lindera-morphology/lindera/pull/164.
=> Rollback meilisearch-tokenizer version

milli/Cargo.toml
This PR bump the tokenizer in v0.2.9 which fixes an issue we had with lindera where reqwest was used with openssl (which was breaking our benchmarks).
=> Bump tokenizer

.github/workflows/push_benchmarks_indexing.yml
This PR fixes the fact that the benchmarks CI on push were [canceled by GitHub](https://github.com/meilisearch/milli/actions/runs/2028844132) because they reached the default timeout of 6h. This PR changes the timeout to 72h, the same setting as the manually triggered benchmark one.
=> Increase benchmarks (push) CI timeout

milli/src/search/mod.rs
I found a bug while working on #473. This pr fixes it and add the missing tests on word derivations.
=> fix bug on 2 typos derivation

milli/src/error.rs, milli/src/index.rs, milli/src/search/mod.rs, milli/src/search/query_tree.rs, milli/src/update/settings.rs, milli/tests/search/mod.rs, milli/tests/search/typo_tolerance.rs
this PR allows the configuration on the minimum word length for typos.
The default values are the same as previously.
=> set minimum word len for typos

Cargo.toml, benchmarks/benches/indexing.rs, benchmarks/benches/utils.rs, cli/src/main.rs, flatten-serde-json/Cargo.toml, flatten-serde-json/README.md, flatten-serde-json/fuzz/Cargo.toml, flatten-serde-json/fuzz/fuzz_targets/flatten.rs, flatten-serde-json/src/lib.rs, flatten-serde-json/src/main.rs, http-ui/src/main.rs, milli/Cargo.toml, milli/src/documents/mod.rs, milli/src/error.rs, milli/src/index.rs, milli/src/lib.rs, milli/src/search/distinct/mod.rs, milli/src/search/facet/facet_distribution.rs, milli/src/search/facet/filter.rs, milli/src/search/mod.rs, milli/src/update/clear_documents.rs, milli/src/update/delete_documents.rs, milli/src/update/index_documents/extract/extract_geo_points.rs, milli/src/update/index_documents/extract/mod.rs, milli/src/update/index_documents/mod.rs, milli/src/update/index_documents/transform.rs, milli/src/update/settings.rs, milli/tests/search/mod.rs, milli/tests/search/query_criteria.rs, milli/tests/search/typo_tolerance.rs
For the following document:
```json
{
"id": 1,
"person": {
"name": "tamo",
"age": 25,
}
}
```
Suppose the user sets `person` as a filterable attribute. We need to store `person` in the filterable _obviously_. But we also need to keep track of `person.name` and `person.age` somewhere.
That’s where I changed a little bit the logic of the engine.
Currently, we have a function called `faceted_field` that returns the union of the filterable and sortable.
I renamed this function in `user_defined_faceted_field`. And now, when we finish indexing documents, we look at all the fields and see if they « match » a `user_defined_faceted_field`.
So in our case:
- does `id` match `person`: 🔴 
- does `person.name` match `person`: 🟢 
- does `person.age` match `person`: 🟢 
And thus, we insert in the …
=> Nested fields

.github/release-draft-template.yml, .github/workflows/enforce-label.yml
- Enforce one of the following labels to make the CI pass: `no breaking`, `DB breaking`, `API breaking` (milli API, not the Meilisearch API of course), or `skip changelog`. This new CI is now `Required` in the GitHub settings for merging a PR.
- Adapt the release drafter to these new labels
- rename `skip-changelog` into `skip changelog` according to the new label name
=> Enforce labelling for the PRs

cli/src/main.rs, milli/src/search/mod.rs, milli/tests/search/distinct.rs
fix https://github.com/meilisearch/meilisearch/issues/2152
I think the issue was that we didn't take off the excluded candidates from the initial candidates when returning the candidates with the search result.
=> fix distinct count bug

flatten-serde-json/Cargo.toml, flatten-serde-json/benches/benchmarks.rs, flatten-serde-json/src/lib.rs
This PR adds some benchmarks to the _flatten-serde-json_ crate, this crate is responsible for transforming the original documents into flat versions that the engine can understand. It can probably be speed-up and this is why I added benchmarks to it.
I make some interesting performance improvements when I replaced the `json!` macro calls.
```
flatten/simple          time:   [452.44 ns 453.31 ns 454.18 ns]
change: [-15.036% -14.751% -14.473%] (p = 0.00 < 0.05)
Performance has improved.
Found 2 outliers among 100 measurements (2.00%)
2 (2.00%) high mild
Benchmarking flatten/complex: Collecting 100 samples in estimated 5.0007 s (4.9M i                                                                                  flatten/complex         time:   [1.0101 us 1.0131 us 1.0160 us]
change: …
```
=> Improve the performances of the flattening subcrate

milli/Cargo.toml, milli/src/update/index_documents/mod.rs, milli/src/update/index_documents/transform.rs
We need to store all the external id (primary key) in a hashmap
associated to their internal id.
The smartstring remove heap allocation / memory usage and should
improve the cache locality.
I ran the benchmarks to measure the impact of this PR on the indexing time.
I think we should merge it whatever happens thought because it'll decrease the memory consumption.
---------
This improve really sliiiiiightly the performances but improve the memory usage thus it should be merged.
```
group                                                             indexing_main_6b073738                 indexing_use-smartsring_3f343511
-----                                                             ----------------------                 --------------------------------
indexing/Indexing geo_point …
```
=> Use smartstring to store the external id in our hashmap

benchmarks/Cargo.toml, benchmarks/benches/formatting.rs, http-ui/src/main.rs, milli/src/lib.rs, milli/src/search/matches/matching_words.rs, milli/src/search/matches/mod.rs, milli/src/search/mod.rs, milli/src/search/query_tree.rs
Enhance milli word-matcher making it handle match computing and cropping.
Before we were considering that the first match of the attribute was the best one, this was accurate when only one word was searched but was missing the target when more than one word was searched.
Now we are searching for the best matches interval to crop around, the chosen interval is the one:
1) that have the highest count of unique matches
> for example, if we have a query `split the world`, then the interval `the split the split the` has 5 matches but only 2 unique matches (1 for `split` and 1 for `the`) where the interval `split of the world` has 3 matches and 3 unique matches. So the interval `split of the world` is considered better.
2) that have the minimum distance between matches
> for example, if we have …
=> Enhance matching words

milli/src/update/settings.rs
fix min word len for typo not resettign properly, as reported in https://github.com/meilisearch/meilisearch/issues/2330
=> fix min-word-len-for-typo not reset properly

benchmarks/scripts/compare.sh
=> Get rid of the threshold when comparing benchmarks

cli/Cargo.toml, helpers/Cargo.toml, http-ui/Cargo.toml, infos/Cargo.toml, milli/Cargo.toml, milli/src/update/settings.rs
Bring 8b14090927d2ee6c0958f29f98cd52b996599c83 into v0.26.2 to avoid releasing milli v0.27.0 containing the croping improvement (#483)
the branch `v0.26.2` is starting from `v0.26.1` and not from the latest commit on `main`
=> v0.26.2 release: includes the typo-tolerance fix

milli/src/update/index_documents/mod.rs
In order to make sure that long words don't break the indexation step of the engine, I added a test. Unfortunately, it doesn't trigger anything bad and so I am not able to find why we have issue https://github.com/meilisearch/meilisearch/issues/2338.
=> Add a test to make sure that long words are handled

bors.toml
Because of multiple issues we had with bors.
https://github.com/bors-ng/bors-ng/issues/1492
=> Remove pr_status from bors settings

milli/src/update/index_documents/mod.rs, milli/src/update/index_documents/transform.rs
When we need to flatten a document:
* The primary key contains a `.`.
* Some fields need to be flattened
Instead of flattening the whole object and thus creating a lot of allocations with the `serde_json_flatten_crate`, we instead generate a minimal sub-object containing only the fields that need to be flattened.
That should create fewer allocations and thus index faster.
---------
```
group                                                             indexing_main_e1e362fa                 indexing_stop-flattening-every-field_40d1bd6b
-----                                                             ----------------------                 ---------------------------------------------
indexing/Indexing geo_point                                       1.99      23.7±0.23s        ? ?/sec …
```
=> Stop flattening every field

benchmarks/Cargo.toml, cli/Cargo.toml, filter-parser/Cargo.toml, flatten-serde-json/Cargo.toml, helpers/Cargo.toml, http-ui/Cargo.toml, infos/Cargo.toml, json-depth-checker/Cargo.toml, milli/Cargo.toml, milli/src/update/index_documents/mod.rs, milli/src/update/index_documents/transform.rs, milli/src/update/settings.rs
`release-v0.26.3` is originated from `v0.26.2` and not from `main`
Add the commits of
- https://github.com/meilisearch/milli/pull/505
- https://github.com/meilisearch/milli/pull/514
And update the version in every concerned files
The tag `v0.26.3` will be created once this PR is merged and will be done on the `release-v0.26.3` branch
=> v0.26.3 release: normalizes exact word

benchmarks/Cargo.toml, cli/Cargo.toml, filter-parser/Cargo.toml, flatten-serde-json/Cargo.toml, helpers/Cargo.toml, http-ui/Cargo.toml, infos/Cargo.toml, json-depth-checker/Cargo.toml, milli/Cargo.toml
Checked with @Kerollmops 
- Update the version into every workspace (the current version is v0.27.0, but I forgot to update it for the previous release)
- add `publish = false` except in `milli` workspace.
=> Update version in every workspace

milli/src/search/facet/facet_distribution.rs, milli/tests/search/facet_distribution.rs, milli/tests/search/mod.rs
This PR is related to https://github.com/meilisearch/meilisearch/issues/2352 and should fix the issue when Meilisearch is up-to-date with this PR.
=> Return facets even when there is no value associated to it

milli/src/update/index_documents/mod.rs, milli/src/update/word_prefix_docids.rs, milli/src/update/word_prefix_pair_proximity_docids.rs, milli/src/update/words_prefix_position_docids.rs
This PR fixes https://github.com/meilisearch/meilisearch/issues/2338 by making sure that we do not generate keys that are too long for LMDB especially when we are creating our prefix and proximity pairs keys.
=> Do not generate keys that are too long for LMDB

milli/src/update/settings.rs
fix settings not being correctly initialized and add a test to make sure that they are in the future.
fix https://github.com/meilisearch/meilisearch/issues/2358
=> fix mistake in Settings initialization

benchmarks/Cargo.toml, cli/Cargo.toml, filter-parser/Cargo.toml, flatten-serde-json/Cargo.toml, helpers/Cargo.toml, http-ui/Cargo.toml, infos/Cargo.toml, json-depth-checker/Cargo.toml, milli/Cargo.toml, milli/src/search/facet/facet_distribution.rs, milli/src/update/index_documents/mod.rs, milli/src/update/settings.rs, milli/src/update/word_prefix_docids.rs, milli/src/update/word_prefix_pair_proximity_docids.rs, milli/src/update/words_prefix_position_docids.rs, milli/tests/search/facet_distribution.rs, milli/tests/search/mod.rs
I cherry-picked the commits from these PRs
- https://github.com/meilisearch/milli/pull/518
- https://github.com/meilisearch/milli/pull/522
- https://github.com/meilisearch/milli/pull/520
`release-v0.26.4` has been started from the tag `v0.26.3` and not from main
The release tag `v0.26.4` will be done on the branch `release-v0.26.4` once this PR is merge
=> Release v0.26.4: returns facets even when there is no value associated to it + bug fix during indexation + bug fix on typo-tolerance

milli/Cargo.toml, milli/src/asc_desc.rs, milli/src/criterion.rs, milli/src/error.rs
I introduced [`thiserror`](https://docs.rs/thiserror/latest/thiserror/) to implements all the `Display` trait and most of the `impl From<xxx> for yyy` in way less lines.
And then I introduced a cute macro to implements the `impl<X, Y, Z> From<X> for Z where Y: From<X>, Z: From<X>` more easily.
=> Simplify the error creation with thiserror

milli/src/criterion.rs
This PR improves the ranking rules error message to properly reflect the case sensitivity.
The issue was highlighted in [meilisearch/issues/2407](https://github.com/meilisearch/meilisearch/issues/2407).
Cheers!
=> Improves ranking rules error message

milli/src/index.rs, milli/src/search/mod.rs, milli/src/search/query_tree.rs, milli/src/update/settings.rs
This PR make `exact_words` return an `Option` instead of an empty set, since set creation is costly, as noticed by @kerollmops.
I was not convinces that this was the cause for all of the performance drop we measured, and then realized that methods that initialized it were called recursively which caused initialization times to add up. While the first fix solves the issue when not using exact words, using exact word remained way more expensive that it should be. To address this issue, the exact words are cached into the `Context`, so they are only initialized once.
=> speedup exact words

milli/src/search/facet/facet_distribution.rs
This PR reintroduces the max values by facet limit this is related to https://github.com/meilisearch/meilisearch/issues/2349.
~I would like some help in deciding on whether I keep the default 100 max values in milli and set up the `FacetDistribution` settings in Meilisearch to use 1000 as the new value, I expose the `max_values_by_facet` for this purpose.~
I changed the default value to 1000 and the max to 10000, thank you @ManyTheFish for the help!
=> Reintroduce the max values by facet limit

milli/src/search/facet/facet_distribution.rs
This PR implements the early draft of the new spec (waiting for it) specifying how the new facet limit feature should work and which limit we apply to the number of facet values to return by facet.
=> Setup the new limits on the number of facet values to return

benchmarks/Cargo.toml, cli/Cargo.toml, filter-parser/Cargo.toml, filter-parser/src/lib.rs, flatten-serde-json/Cargo.toml, helpers/Cargo.toml, http-ui/Cargo.toml, infos/Cargo.toml, json-depth-checker/Cargo.toml, milli/Cargo.toml, milli/src/search/facet/filter.rs
Will fix https://github.com/meilisearch/meilisearch/issues/2380
The issue was that in the evaluation of the filter, I was using the deref implementation instead of calling the `value` method of my token.
To avoid the problem happening again, I removed the deref implementation; now, you need to either call the `lexeme` or the `value` methods but can't rely on a « default » implementation to get a string out of a token.
=> Fix escaped quotes in filter

cli/src/main.rs, infos/src/main.rs, milli/src/index.rs, milli/src/update/delete_documents.rs
Poke @irevoire, we may merge this into your branch.
=> Ensure that Index methods are not bypassed by Meilisearch

benchmarks/Cargo.toml, benchmarks/benches/indexing.rs
Add benchmarks on the deletion and start rethinking benchmark names.
=> Deletion benchmarks

milli/src/search/mod.rs
This PR is related to https://github.com/meilisearch/meilisearch/issues/2532 but it doesn't fix it entirely. It improves it by computing the excluded documents (the ones with an already-seen distinct value) before stopping the loop, I think it was a mistake and should always have been this way.
The reason it doesn't fix the issue is that Meilisearch is lazy, just to be sure not to compute too many things and answer by taking too much time. When we deduplicate the documents by their distinct value we must do it along the water, everytime we see a new document we check that its distinct value of it doesn't collide with an already returned document. 
The reason we can see the correct result when enough documents are fetched is that we were lucky to see all of the different distinct values …
=> Improve the `estimatedNbHits` when a `distinctAttribute` is specified

milli/src/index.rs
Meilisearch needs this method to do snapshots.
=> Introduce the copy_to_path method on the Index

milli/src/search/facet/filter.rs, milli/tests/search/filters.rs, milli/tests/search/mod.rs
Related to https://github.com/meilisearch/meilisearch/issues/2516
Looks like the issue should be moved to this repo, but I'm not sure what the right procedure for it.
=> Fix not equal filter when field contains both number and strings

benchmarks/benches/utils.rs
Previously, the first document in the NDJson file was read over and over again. So the `geo_point` benchmark was not working properly: it only indexed one document.
=> Fix deserialisation of NDJson documents in benchmarks

benchmarks/benches/indexing.rs
With #557 coming, we should add benchmarks that measure our impact on the reindexing process.
=> Add reindexing benchmarks

milli/Cargo.toml, milli/src/update/index_documents/transform.rs
Just to [align the version with Meilisearch](https://github.com/meilisearch/meilisearch/pull/2584).
=> Bump uuid to 1.1.2

benchmarks/benches/indexing.rs
The `movies.json` file in the benchmark datasets contains a filterable field called "release_date", but the indexing benchmarks wrongly called the field "released_date" instead. This PR fixes that.
=> Fix name of "release_date" facet in movies benchmarks

benchmarks/Cargo.toml, cli/Cargo.toml, filter-parser/Cargo.toml, flatten-serde-json/Cargo.toml, helpers/Cargo.toml, http-ui/Cargo.toml, infos/Cargo.toml, json-depth-checker/Cargo.toml, milli/Cargo.toml, milli/src/search/matches/mod.rs
In the case of only 1 query word was matching in an attribute,
and this same word was matching several times in the crop window of the same attribute,
then only the first match was highlighted.
Now we ensure that the computed "best matches interval" contains all the words that match in the same crop window.
related to https://github.com/meilisearch/meilisearch/issues/2627
=> Fix(smart-crop): Ensure that matches are all highlighted

benchmarks/Cargo.toml, cli/Cargo.toml, filter-parser/Cargo.toml, flatten-serde-json/Cargo.toml, helpers/Cargo.toml, http-ui/Cargo.toml, infos/Cargo.toml, json-depth-checker/Cargo.toml, milli/Cargo.toml
In order to release on `main` (for v0.29.0, not v0.28.1)
=> Update version for next release (v0.32.0)

milli/src/update/index_documents/enrich.rs, milli/src/update/index_documents/mod.rs
fix #592
related to https://github.com/meilisearch/meilisearch/issues/2640
=> fix: Remove whitespace trimming during document id validation

Cargo.toml
Using `codegen-units = 1` and `lto = 'thin'` makes the compile time a bit longer, but also produces faster binaries.
I'd like to run milli's benchmark with these options, so that we can see whether it is worth enabling on meilisearch.
=> Make binaries faster on release profile through better compile options

milli/src/search/criteria/mod.rs, milli/src/search/criteria/proximity.rs
This bug is an old bug but was hidden by the proximity criterion,
Phrase searches were always returning an empty candidates list when the proximity criterion is deactivated.
Before the fix, we were trying to find any words[n] near words[n]
instead of finding  any words[n] near words[n+1], for example:
for a phrase search '"Hello world"' we were searching for "hello" near "hello" first, instead of "hello" near "world".
=> Fix(Search): Fix phrase search candidates computation

milli/src/update/index_documents/mod.rs, milli/src/update/index_documents/transform.rs
When we replaced or updated some documents, the indexing was skipping the replaced documents.
Related to https://github.com/meilisearch/meilisearch/issues/2672
=> Fix soft deleted documents

benchmarks/benches/indexing.rs, benchmarks/benches/utils.rs, cli/Cargo.toml, cli/src/main.rs, helpers/Cargo.toml, helpers/src/main.rs, http-ui/Cargo.toml, http-ui/src/main.rs, http-ui/src/update_store.rs, infos/Cargo.toml, infos/src/main.rs, milli/Cargo.toml, milli/src/error.rs, milli/src/index.rs, milli/src/update/delete_documents.rs, milli/src/update/index_documents/mod.rs
Fixes #570 
This PR tries to improve the threshold used to trigger the real deletion of documents.
The deletion is now triggered in two cases;
- 10% of the total available space is used by soft deleted documents
- 90% of the total available space is used.
In this context, « total available space » means the `map_size` of lmdb.
And the size used by the soft deleted documents is actually an estimation. We can't determine precisely the size used by one document thus what we do is; take the total space used, divide it by the number of documents + soft deleted documents to estimate the size of one average document. Then multiply the size of one avg document by the number of soft deleted document.
--------
Here we can see we have a ~10GB drift in the end between the space used by the soft …
=> Better threshold

benchmarks/Cargo.toml, milli/fuzz/Cargo.toml, milli/fuzz/fuzz_targets/indexing.rs
Use the reexported version of heed in the benchmarks and the fuzzer
=> Share heed between all sub-crates

benchmarks/benches/utils.rs, milli/src/lib.rs, milli/src/search/mod.rs, milli/src/search/query_tree.rs, milli/src/update/index_documents/mod.rs, milli/tests/search/distinct.rs, milli/tests/search/filters.rs, milli/tests/search/mod.rs, milli/tests/search/query_criteria.rs, milli/tests/search/sort.rs, milli/tests/search/typo_tolerance.rs
Implement several optional words strategy.
Replace `optional_words` boolean with an enum containing several term matching strategies:
```rust
pub enum TermsMatchingStrategy {
// remove last word first
Last,
// remove first word first
First,
// remove more frequent word first
Frequency,
// remove smallest word first
Size,
// only one of the word is mandatory
Any,
// all words are mandatory
All,
}
```
All strategies implemented during the prototype are kept, but only `Last` and `All` will be published by Meilisearch in the `v0.29.0` release.
spec: https://github.com/meilisearch/specifications/pull/173
prototype discussion: https://github.com/meilisearch/meilisearch/discussions/2639#discussioncomment-3447699
=> Matching query terms policy

bors.toml
Remove the required windows test for merging due to the issue with Lindera
https://github.com/meilisearch/milli/runs/7970141278?check_suite_focus=true
=> Remove Bors required test for Windows

milli/src/documents/builder.rs
This PR is related to https://github.com/meilisearch/meilisearch/issues/2723 and will fix when this PR will be merged, a new release deployed and used in Meilisearch itself.
This PR makes the indexer to try to parse the values of the fields identified as numbers i.e. `id:number` as integer first then as float if it fails.
=> Accept integers as document ids again

.github/workflows/update-cargo-toml-version.yml
Add a CI we can trigger manually to create a PR updating the Milli version
The next step is to create a Slack bot that will trigger this CI
In the meantime, we can trigger this CI manually in the [Actions tab](https://github.com/meilisearch/milli/actions)
The `MEILI_BOT_GH_PAT` secrets has been added to the organization level, and is accessible for the following repositories (so far): Meilisearch, Milli and Charabia
=> Add CI to update the Milli version

bors.toml
Reverts meilisearch/milli#612
Because the issue does not seem to be there!
Closes https://github.com/meilisearch/milli/issues/614
=> Revert "Remove Bors required test for Windows"

.github/workflows/rust.yml, bors.toml
Ubuntu-18.04 is going to be deprecated by GitHub
https://github.com/actions/runner-images/issues/6002
=> Upgrade ubuntu-18.04 to 20.04

milli/Cargo.toml
Fixes [#627](https://github.com/meilisearch/milli/issues/627#issuecomment-1239769122)
=> Make charabia default feature optional

milli/src/update/index_documents/mod.rs
This PR is related to https://github.com/meilisearch/meilisearch/issues/2764 and should fix it when merged into Meilisearch.
=> We avoid skipping errors in the indexing pipeline

milli/Cargo.toml, milli/src/update/index_documents/extract/extract_docid_word_positions.rs, milli/src/update/index_documents/extract/extract_facet_number_docids.rs, milli/src/update/index_documents/extract/extract_facet_string_docids.rs, milli/src/update/index_documents/extract/extract_fid_docid_facet_values.rs, milli/src/update/index_documents/extract/extract_fid_word_count_docids.rs, milli/src/update/index_documents/extract/extract_word_docids.rs, milli/src/update/index_documents/extract/extract_word_pair_proximity_docids.rs, milli/src/update/index_documents/extract/extract_word_position_docids.rs, milli/src/update/index_documents/helpers/grenad_helpers.rs, milli/src/update/index_documents/mod.rs, milli/src/update/index_documents/transform.rs, milli/src/update/word_prefix_docids.rs, milli/src/update/words_prefix_position_docids.rs
Use an unstable algorithm to sort the internal vector used by `grenad::Sorter` whenever possible to speed up indexing.
In practice, every time the merge function creates a `RoaringBitmap`, we use an unstable sort. For every other merge function, such as `keep_first`, `keep_last`, etc., a stable sort is used.
=> Use an unstable algorithm for `grenad::Sorter` when possible

Cargo.toml
Since we can't enable it in Meilisearch (see https://github.com/meilisearch/meilisearch/pull/2717 ), we should not enable it in milli either. The goal is for milli's benchmarks to accurately represent its performance within meilisearch.
=> Remove LTO in release profile

milli/src/update/index_documents/extract/extract_word_pair_proximity_docids.rs
Fixes https://github.com/meilisearch/milli/issues/647
- During [the increase of the current word position](https://github.com/meilisearch/milli/blob/d94339a85870ece8209e6015234ba72261ab9f4b/milli/src/update/index_documents/extract/extract_word_pair_proximity_docids.rs#L129-L135) we extract the proximity between the current position and the next one.
=> Add proximity calculation for the same word

Cargo.toml, benchmarks/Cargo.toml, cli/Cargo.toml, milli/src/documents/mod.rs
Note: this draft PR is based on https://github.com/meilisearch/milli/pull/601 , for no particular reason.
Make a series of changes with the goal of speeding up debug builds:
1. Add an `all_languages` feature which compiles charabia with its `default` features activated.
The `all_languages` feature is activated by default. But running:
```
cargo build --no-default-features
```
on `milli` is now much faster.
2. Reduce the debug optimisation level from 3 to 0, except for a few critical dependencies.
3.  Compile the build dependencies quicker as well. Previously, all build dependencies were compiled with `opt-level = 3`. Now, only the critical build dependencies are compiled with optimisations.
4. Reduce the amount of code generated by the `documents!` macro
5. Make the "progress update" …
=> Speed up debug builds

milli/src/search/query_tree.rs
Fixes #648 
- [split_best_frequency](https://github.com/meilisearch/milli/blob/55d889522b8b5b6e3dc6d5cf8d14a4f7f62c956b/milli/src/search/query_tree.rs#L282-L301) to use frequency of word pairs near together with proximity value of 1 instead of considering the frequency of individual words. Word pairs having max frequency are considered.
=> Enhance word splitting strategy

milli/src/search/criteria/initial.rs, milli/src/search/criteria/mod.rs, milli/src/search/criteria/typo.rs, milli/src/search/distinct/facet_distinct.rs, milli/src/search/mod.rs, milli/tests/search/query_criteria.rs
Add a new setting `exhaustive_number_hits` to `Search` forcing the `Initial` criterion to exhaustively compute the bucket_candidates allowing the end users to implement finite pagination.
related to https://github.com/meilisearch/meilisearch/pull/2601
=> Add settings to force milli to exhaustively compute the total number of hits

milli/src/asc_desc.rs, milli/src/documents/builder.rs, milli/src/documents/mod.rs, milli/src/fields_ids_map.rs, milli/src/heed_codec/facet/facet_string_level_zero_value_codec.rs, milli/src/heed_codec/facet/facet_string_zero_bounds_value_codec.rs, milli/src/index.rs, milli/src/lib.rs, milli/src/search/criteria/asc_desc.rs, milli/src/search/criteria/attribute.rs, milli/src/search/criteria/geo.rs, milli/src/search/criteria/initial.rs, milli/src/search/criteria/mod.rs, milli/src/search/criteria/proximity.rs, milli/src/search/criteria/typo.rs, milli/src/search/criteria/words.rs, milli/src/search/facet/facet_distribution.rs, milli/src/search/facet/filter.rs, milli/src/search/matches/matching_words.rs, milli/src/search/matches/mod.rs, milli/src/search/query_tree.rs, milli/src/update/delete_documents.rs, milli/src/update/facets.rs, milli/src/update/index_documents/enrich.rs, milli/src/update/index_documents/extract/extract_docid_word_positions.rs, milli/src/update/index_documents/extract/extract_fid_docid_facet_values.rs, milli/src/update/index_documents/extract/mod.rs, milli/src/update/prefix_word_pairs/prefix_word.rs, milli/src/update/prefix_word_pairs/word_prefix.rs
This brings us a step closer to enforcing clippy on each build.
This does not fix any issue outright, but it is a second round of fixes for clippy after https://github.com/meilisearch/milli/pull/665. This should contribute to fixing https://github.com/meilisearch/milli/pull/659.
Satisfies many issues for clippy. The complaints are mostly:
* Passing reference where a variable is already a reference.
* Using clone where a struct already implements `Copy`
* Using `ok_or_else` when it is a closure that returns a value instead of using the closure to call function (hence we use `ok_or`)
* Unambiguous lifetimes don't need names, so we can just use `'_`
* Using `return` when it is not needed as we are on the last expression of a function.
Please check if your PR fulfills the following …
=> Fix many Clippy errors part 2

milli/src/search/criteria/attribute.rs, milli/src/search/criteria/exactness.rs, milli/src/search/criteria/mod.rs, milli/src/search/criteria/proximity.rs, milli/src/search/criteria/typo.rs, milli/src/search/query_tree.rs, milli/tests/search/mod.rs, milli/tests/search/phrase_search.rs
This a WIP draft PR I wanted to create to let other potential contributors know that I'm working on this issue. I'll be completing this in a few hours from opening this.
Fixes #661 and towards fixing meilisearch/meilisearch#2905
=> Fix phrase search containing stop words

filter-parser/src/error.rs, filter-parser/src/lib.rs
`Fixes` https://github.com/meilisearch/meilisearch/issues/3004
- Improves correct error msg in response
=> chore: added `IN`,`NOT IN` to `invalid_filter` msg

.github/workflows/rust.yml
With #676 I noticed the tests were not running in any of our sub crates.
Most of our sub crates didn't includes any tests though.
But the filter-parser did and we're lucky we never broke these one without noticing 😁
=> run the tests in all workspaces

filter-parser/src/error.rs, filter-parser/src/lib.rs, milli/src/search/facet/filter.rs
Related meilisearch/meilisearch#3000
- Filters using `field = inf`, (or `infinite`, `NaN`) now match the value as a string rather than returning an internal error.
- Filters using `field < inf` (or other comparison operators) now return an invalid_filter error rather than returning an internal error, much like when using `field < aaa`.
- Add new `NonFiniteFloat` error variants to the filter-parser errors
- Add `Token::parse_as_finite_float` that can fail both when the string is not a float and when the float is not finite
- Refactor `Filter::inner_evaluate` to always use `parse_as_finite_float` instead of just `parse`
- Add corresponding tests
=> Handle non-finite floats consistently in filters

milli/Cargo.toml
After investigating https://github.com/meilisearch/meilisearch/issues/3017, we found out that it was due to lmdb and that, without any code change on our side, bumping using the lmdb-master-3 branch fix our issues.
But, we’re not really confident about what changed between the `mdb.master` and `mdb.master3` branches; thus this is a temporary change, and we hope we’ll be able to move to the new version of heed asap (either before the end of the pre-release or for the next release).
--------
The bug is hard to reproduce; I can reproduce it 100% of the time on my archlinux personal computer. But on a scaleway archlinux bare-metal machine, it doesn’t reproduce. It’s flaky on our test suite, but @loiclec was able to write a minimal test that reproduces it every time on macOS.
Basically, what …
=> use the lmdb-master.3 branch

.github/workflows/rust.yml, milli/Cargo.toml
Related to https://github.com/meilisearch/meilisearch/issues/3017: will fix once ported to milli and meilisearch.
- Force using vendored version of LMDB
- **don't use lmdb master3 branch anymore**: this is a bit of a side effect of using a tag instead of branch for heed as a dependency, but it is wanted anyway for now as lmdb master3 was more of an experiment
- **modifies CI to run `cargo check` on the release rather than the debug artifacts**. This is an attempt to reduce the necessary disk space and avoid "out of space" failures.
=> Force vendoring of LMDB even if a system version is available

milli/src/update/facet/bulk.rs, milli/src/update/facet/incremental.rs, milli/src/update/index_documents/extract/extract_facet_number_docids.rs, milli/src/update/index_documents/extract/extract_facet_string_docids.rs, milli/src/update/index_documents/extract/extract_fid_docid_facet_values.rs, milli/src/update/index_documents/helpers/mod.rs, milli/src/update/index_documents/mod.rs
1. Handle keys with variable length correctly
Closes (partially) https://github.com/meilisearch/meilisearch/issues/3042 
This issue is now easily reproducible with the updated fuzz tests, which now generate keys with variable lengths.
2. Prevent adding facets to the database if their encoded value does not satisfy `valid_lmdb_key`.
Closes (partially) https://github.com/meilisearch/meilisearch/issues/2743
This fixes an indexing failure when a document had a filterable attribute containing a value whose length is higher than ~500 bytes. For now, this fix is just meant to prevent crashes. Better handling of long values of filterable attributes will be handled in a separate PR.
=> Fix Facet Indexing bugs

milli/src/update/prefix_word_pairs/mod.rs, milli/src/update/prefix_word_pairs/snapshots/mod.rs/test_batch_bug_3043/prefix_word_pair_proximity_docids.snap, milli/src/update/prefix_word_pairs/snapshots/mod.rs/test_batch_bug_3043/word_pair_proximity_docids.snap, milli/src/update/prefix_word_pairs/snapshots/mod.rs/test_batch_bug_3043/word_prefix_pair_proximity_docids.snap, milli/src/update/prefix_word_pairs/word_prefix.rs
Where the batch's information was not properly updated in cases where only the proximity changed between two consecutive word pair proximities.
Closes partially https://github.com/meilisearch/meilisearch/issues/3043
=> Fix bug in prefix DB indexing

.github/workflows/rust.yml
This PR changes the CI to use Rust stable for Clippy. This way we will reduce the number of times we break the CI. [The version will only change every two months or so](https://www.whatrustisit.com/).
We can't do it for rustfmt yet. See: https://github.com/meilisearch/milli/pull/710#discussion_r1031654931
=> Update Clippy to use Rust Stable

.github/workflows/manual_benchmarks.yml, .github/workflows/push_benchmarks_indexing.yml, .github/workflows/push_benchmarks_search_geo.yml, .github/workflows/push_benchmarks_search_songs.yml, .github/workflows/push_benchmarks_search_wiki.yml
Fixes #678
- Replace deprecated github action command with newly defined command.
=> Replace deprecated gh actions

milli/src/update/facet/bulk.rs, milli/src/update/facet/incremental.rs
Fixes (partially, until merged into meilisearch) https://github.com/meilisearch/meilisearch/issues/3165
Fixes a bug where indexing certain numbers of filterable attribute values in bulk led to corrupted facet databases. This was due to a lossy integer conversion which would ultimately prevent entire levels of the facet database to be written into LMDB.
More specifically, this change was made:
```diff
- if cur_writer_len as u8 >= self.min_level_size {
+ if cur_writer_len >= self.min_level_size as usize {
```
I also checked other comparisons to `min_level_size` and other conversions such as `x as u8` in this part of the codebase.
=> Fix bulk facet indexing bug

benchmarks/benches/formatting.rs, milli/src/lib.rs, milli/src/search/matches/matching_words.rs, milli/src/search/matches/mod.rs, milli/src/search/query_tree.rs, milli/src/update/index_documents/extract/extract_docid_word_positions.rs, milli/src/update/index_documents/extract/extract_facet_string_docids.rs, milli/src/update/index_documents/extract/extract_fid_docid_facet_values.rs, milli/src/update/index_documents/helpers/mod.rs
Fixes (partially) https://github.com/meilisearch/meilisearch/issues/3115 
1. Reduces the memory usage caused by the creation of a 10-word query tree by 20x. 
This is done by deduplicating the `MatchingWord` values, which are heavy because of their inner DFA. The deduplication works by wrapping each `MatchingWord` in a reference-counted box and using a hash map to determine whether a  `MatchingWord` DFA already exists for a certain signature, or whether a new one needs to be built.
2. Avoid the worst-case scenario of creating a `MatchingWord` for extremely long words that cannot be indexed by milli.
=> Reduce memory usage of the MatchingWords structure

milli/src/index.rs, milli/src/update/settings.rs
When updating index settings using `update::Settings`, sometimes a `reindex` of `update::Settings` is triggered when it doesn't need to be. This PR aims to prevent those unnecessary `reindex` calls.
For reference, here is a snippet from the current `execute` method in `update::Settings`:
```rust
// ...
if stop_words_updated
|| faceted_updated
|| synonyms_updated
|| searchable_updated
|| exact_attributes_updated
{
self.reindex(&progress_callback, &should_abort, old_fields_ids_map)?;
}
```
=> Limit the reindexing caused by updating settings when not needed

milli/src/search/facet/filter.rs
Fixes #3167 (https://github.com/meilisearch/meilisearch/issues/3167)
- allows Geosearch with zero radius to return the specified location when the coordinates match perfectly (instead of returning nothing). See link for more details.
- new attempt on https://github.com/meilisearch/milli/pull/713
- [ X ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ X ] Have you read the contributing guidelines?
- [ X ] Have you made sure that the title is accurate and descriptive of the changes?
=> Geosearch for zero radius

milli/src/search/criteria/asc_desc.rs, milli/src/search/criteria/attribute.rs, milli/src/search/criteria/exactness.rs, milli/src/search/criteria/final.rs, milli/src/search/criteria/geo.rs, milli/src/search/criteria/initial.rs, milli/src/search/criteria/mod.rs, milli/src/search/criteria/proximity.rs, milli/src/search/criteria/typo.rs, milli/src/search/criteria/words.rs, milli/src/search/mod.rs, milli/tests/search/distinct.rs
This PR changes the name and behavior of `bucket_candidates`:
- `bucket_candidates` become `initial_candidates` that is less confusing
- `initial_candidates` is no more a simple `RoaringBitmap` but an enum allowing us to precise if the candidates are exhaustive or not
- this enum ensures that any modification is allowed only if the candidates are not already exhaustive.
The bug occurred because `initial_candidates` are modified during the bucket sort allowing the estimation to be more and more precise along the search, and this was an issue when the `initial_candidates` were already exhaustive, now, if candidates are exhaustive, then no modifications are made.
=> Fix distincted exhaustive hits

milli/src/index.rs, milli/src/update/delete_documents.rs, milli/src/update/index_documents/mod.rs
Fixes (partially, until merged into meilisearch) https://github.com/meilisearch/meilisearch/issues/2945 (until we integrate the new milli bump into meilisearch).
**Note that a dump will not be sufficient to upgrade from meilisearch v0.30.2 to meilisearch v0.30.3 due to this fix** because the bug could have caused the `documents` database to be corrupted. Instead, a full manual reimport of the documents will be necessary.
There was a bug happening when:
1. A few documents are added to the index
2. Some of these documents are soft-deleted
3. New documents are added, replacing existing ones and triggering a hard-deletion
The `IndexDocuments::execute` method would then perform the hard-deletion but forget to change the `external_document_ids` structure appropriately. As a result, the …
=> Fix bug 2945/3021 (missing key in documents database)

milli/src/search/criteria/typo.rs, milli/src/search/criteria/words.rs
When `Typo` criterion was after a different criterion than `Words` and the previous criterion wasn't returning any candidates at the first iteration of the bucket sort, then the `initial_candidates` were lost.
Now, `Typo`ensure to keep the `initial_candidates` between iterations.
related to https://github.com/meilisearch/meilisearch/issues/3200#issuecomment-1345179578
related to https://github.com/meilisearch/meilisearch/issues/3228
=> Fix typo initial candidates computation

filter-parser/src/error.rs, filter-parser/src/lib.rs
Currently, we have these two errors on rust nightly. It would be nice to help rustc understand what's going on
```
error[E0658]: anonymous lifetimes in `impl Trait` are unstable
--> filter-parser/src/lib.rs:173:53
|
173 | fn ws<'a, O>(inner: impl FnMut(Span<'a>) -> IResult<O>) -> impl FnMut(Span<'a>) -> IResult<O> {
|                                                     ^ expected named lifetime parameter
|
= help: add `#![feature(anonymous_lifetime_in_impl_trait)]` to the crate attributes to enable
help: consider introducing a named lifetime parameter
|
173 | fn ws<'a, 'a, O>(inner: impl FnMut(Span<'a>) -> IResult<'a, O>) -> impl FnMut(Span<'a>) -> IResult<O> {
|       +++                                               +++
error[E0658]: anonymous lifetimes in `impl Trait` are unstable
--> …
```
=> Fix two nightly errors

milli/src/search/criteria/asc_desc.rs
This is simply an integration test ensuring that the sort criterion works properly. 
However, only one version of the algorithm is tested here (the iterative one). To test the version that uses the facet DB, one has to manually set the `CANDIDATES_THRESHOLD` constant to `0`. I have done that and ensured that the test still succeeds. However, in the future, we will probably want to have an option to force which algorithm is used at runtime, for testing purposes.
=> Add some integration tests on the sort criterion

milli/src/search/criteria/initial.rs
this bug is reproducible on real datasets and is hard to isolate in a simple test.
related to: https://github.com/meilisearch/meilisearch/issues/3200
poke @curquiza
=> Fix finite pagination with placeholder search

milli/src/external_documents_ids.rs, milli/src/index.rs, milli/src/update/delete_documents.rs
Fixes (when merged into meilisearch) https://github.com/meilisearch/meilisearch/issues/3021
There was a bug happening when:
1. Documents were added
2. Some of these documents were replaced using soft-deletion
3. A deletion of another non-replaced document takes place and triggers a hard-deletion
4. Documents with the same identifiers as the replaced documents are added again
Then, search results would return duplicate documents. No crash would happen at any time (this is the reason it wasn't caught by the previous fuzz test. I have updated the new one such that it also checks the result of a placeholder search request, which then finds the bug immediately).
The cause of the bug is: 
1. When a hard-deletion is triggered, we try to retrieve the external document id associated with each …
=> Fix hard-deletion of an external id that was soft-deleted and then reimported - main

milli/src/external_documents_ids.rs, milli/src/index.rs, milli/src/update/delete_documents.rs
This is a PR that cherry-picks the commit from https://github.com/meilisearch/milli/pull/750 onto `release-v0.37.5`
=> Fix hard-deletion of an external id that was soft-deleted and then reimported - release-v0.37.5

cli/src/main.rs, milli/src/lib.rs, milli/src/search/criteria/asc_desc.rs, milli/src/search/criteria/attribute.rs, milli/src/search/criteria/mod.rs, milli/src/search/criteria/proximity.rs, milli/src/search/mod.rs
Add a parameter to search requests which determines the implementation strategy of the criteria. This can be either `set-based`, `iterative`, or `dynamic` (ie choosing between set-based or iterative at search time). See https://github.com/meilisearch/milli/issues/755 for more context about this change.
=> Add a "Criterion implementation strategy" parameter to Search

milli/src/error.rs, milli/src/update/index_documents/enrich.rs, milli/src/update/index_documents/mod.rs, milli/src/update/index_documents/transform.rs
Related to https://github.com/meilisearch/meilisearch/issues/3233
- Change primary key inference to only consider a value as a candidate when it ends with "id", rather than when it simply contains "id".
- Change primary key inference to always fail when there are multiple candidates.
- Replace UserError::MissingPrimaryKey with `UserError::NoPrimaryKeyCandidateFound` and `UserError::MultiplePrimaryKeyCandidatesFound`
- Remove uses of UserError::MissingPrimaryKey not pertaining to inference. This introduces a possible panicking path.
=> Simplify primary key inference

milli/src/search/criteria/exactness.rs
Fixes (partially) https://github.com/meilisearch/meilisearch/issues/3116
1. Reduces the algorithmic complexity of finding the documents containing N exact words from something that is exponential to something that is polynomial.
2. Cache intermediary results between different calls to the `exactness` criterion.
On the `smol_songs.csv` dataset, a request containing 10 common words now takes about 60ms instead of 5 seconds to execute. For example, this is the case with this (admittedly nonsensical) request: `Rock You Hip Hop Folk World Country Electronic Love The`.
=> Optimise the `ExactWords` sub-criterion within `Exactness`

milli/src/search/query_tree.rs
Fixes (when merged into meilisearch) https://github.com/meilisearch/meilisearch/issues/3125
We now map multi-word synonyms to phrases instead of loose words. Such that the request:
```
btw I am going to nyc soon
```
is interpreted as (when the synonym interpretation is chosen for both `btw` and `nyc`):
```
"by the way" I am going to "New York City" soon
```
instead of:
```
by the way I am going to New York City soon
```
This prevents queries containing multi-word synonyms to exceed to word length limit and degrade the search performance.
In terms of relevancy, there is a debate to have. I personally think this could be considered an improvement, since it would be strange for a user to search for:
```
good DIY project
```
and have a result such as:
```
{
"text": "whether it is a good …
```
=> Interpret synonyms as phrases

milli/src/search/criteria/mod.rs, milli/src/search/criteria/proximity.rs, milli/src/update/mod.rs, milli/src/update/prefix_word_pairs/mod.rs
Somewhat fixes (until merged into meilisearch) https://github.com/meilisearch/meilisearch/issues/3118
When a query ends with a word and a prefix, such as:
```
word pr
```
Then we first determine whether `pre` *could possibly* be in the proximity prefix database before querying it. There are then three possibilities:
1. `pr` is not in any prefix cache because it is not the prefix of many words. We don't query the proximity prefix database. Instead, we list all the word derivations of `pre` through the FST and query the regular proximity databases.
2. `pr` is in the prefix cache but cannot be found in the proximity prefix databases. **In this case, we partially disable the proximity ranking rule for the pair `word pre`.** This is done as follows:
1. Only find the documents where `word` is …
=> Avoid a prefix-related worst-case scenario in the proximity criterion

milli/src/index.rs
Related to discussion: https://github.com/meilisearch/meilisearch/discussions/3280
- Expose `heed::Env::map_size` through `Index::map_size`. This allows knowing after the fact with which `map_size` an environment was opened (which is not always the `map_size` that was configured for the opening of the environment, see the documentation for `Index::map_size`), which will be necessary to guarantee we can reopen the index with a larger `map_size`.
=> Add Index::map_size

benchmarks/benches/utils.rs, cli/src/main.rs, milli/Cargo.toml, milli/src/search/criteria/asc_desc.rs, milli/src/search/criteria/exactness.rs, milli/src/search/criteria/proximity.rs, milli/src/update/settings.rs, milli/tests/search/mod.rs, milli/tests/search/query_criteria.rs
1. `Setting<T>` now implements `DeserializeFromValue`
2. The settings now store ranking rules as strongly typed `Criterion` instead of `String`, since the validation of the ranking rules will be done on meilisearch's side from now on
=> Integrate deserr

milli/Cargo.toml, milli/src/update/settings.rs
Update deserr to 0.1.5, which changes the `DeserializeFromValue` trait, getting rid of the `default()` method.
=> Update deserr to latest version

milli/src/index.rs, milli/src/snapshots/index.rs/bug_3007/geo_faceted_documents_ids.snap, milli/src/update/index_documents/enrich.rs, milli/src/update/index_documents/mod.rs
Fixes partially [#3007](https://github.com/meilisearch/meilisearch/issues/3007)
- Changes function validate_geo_from_json to return a BadLatitudeAndLongitude if lat or lng is a string and not parseable to f64
- implemented some unittests
- Derived PartialEq for GeoError to use assert_eq! in tests
=> Fixes error message when lat and lng are unparseable

milli/src/error.rs, milli/src/index.rs, milli/src/snapshots/index.rs/unexpected_extra_fields_in_geo_field/geo_faceted_documents_ids.snap, milli/src/update/index_documents/enrich.rs
Fix parts of https://github.com/meilisearch/meilisearch/issues/3414
=> Throw an error on unknown fields specified in the _geo field

.github/workflows/rust.yml, milli/src/index.rs, milli/src/search/criteria/proximity.rs, milli/src/search/criteria/typo.rs, milli/src/update/delete_documents.rs, milli/src/update/facet/incremental.rs, milli/src/update/index_documents/helpers/grenad_helpers.rs, milli/src/update/index_documents/transform.rs, milli/tests/search/phrase_search.rs
milli part of https://github.com/meilisearch/meilisearch/pull/3437
=> Fix clippy for Rust 1.67, allow `uninlined_format_args`

milli/src/update/words_prefix_position_docids.rs
Fixes partially https://github.com/meilisearch/milli/issues/605
The `words_prefix_position_docids` can easily contain millions of entries. Thus, iterating
over it can be very expensive. But we do so needlessly for every document addition tasks.
It can sometimes cause indexing performance issues when :
- a user sends many `documentAdditionOrUpdate` tasks that cannot be all batched together (for example if they are interspersed with `documentDeletion` tasks)
- the documents contain long, diverse text fields, thus increasing the number of entries in `words_prefix_position_docids`
- the index has accumulated many soft-deleted documents, further increasing the size of `words_prefix_position_docids`
- the machine running Meilisearch does not have great IO performance (e.g. slow SSD, or …
=> Reduce incremental indexing time of `words_prefix_position_docids` DB

milli/src/search/criteria/attribute.rs
Fixes https://github.com/meilisearch/meilisearch/issues/3483 for v1.0.1
=> Fix attributes set candidates

milli/src/search/query_tree.rs, milli/tests/search/phrase_search.rs
A search with a phrase containing only stop words was returning an HTTP error 500,
this PR filters the phrase containing only stop words dropping them before the search starts, a query with a phrase containing only stop words now behaves like a placeholder search.
fixes https://github.com/meilisearch/meilisearch/issues/3521 for v1.0.2
related v1.1.0 PR on Meilisearch: https://github.com/meilisearch/meilisearch/pull/3525
=> Fix phrase search containing only stop words
